using RIT.HMS.Data;
using RIT.HMS.Domain;
using RIT.HMS.Domain.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;


namespace RIT.HMS.BLL.Common
{
    public class BLL_AutoGeneratedInfo
    {
        private readonly UnitOfWork _untofwork;

        public BLL_AutoGeneratedInfo()
        {
            _untofwork = new UnitOfWork();
        }
        public BLL_AutoGeneratedInfo(string connection)
        {
            _untofwork = new UnitOfWork(connection);
        }
        public  AutoGenerateInfo GetAutoGenerateInfoByForm(string formName,int companyid)
        {
            AutoGenerateInfo autoGenerateInfo = new AutoGenerateInfo();
            try
            {
                if (_untofwork.AutoGeneratedInfoRepository.Get(ai => ai.FormName == formName).FirstOrDefault() != null)
                {
                    autoGenerateInfo = _untofwork.AutoGeneratedInfoRepository.Get(ai => ai.FormName == formName 
                                                                                  && ai.CompanyId==companyid).FirstOrDefault();
                }

                if (string.IsNullOrEmpty(autoGenerateInfo.FormText))
                {
                    autoGenerateInfo.FormText = "Select a Caption";
                }

                return autoGenerateInfo;
            }
            catch (Exception ex)
            {
                throw;
            }
           
        }
    }
}