using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Text;
using System.Web;
//using MoreLinq;
using EntityFramework.Extensions;
using RIT.HMS.Domain;
using RIT.HMS.Data;
using RIT.HMS.Domain.Common;

namespace RIT.HMS.BLL.Common
{
    public class BLL_Common
    {
        private readonly UnitOfWork _unitofwork;
        BLL_AutoGeneratedInfo autoGenInfoServ;
        public BLL_Common()
        {
            _unitofwork = new UnitOfWork();
            autoGenInfoServ = new BLL_AutoGeneratedInfo();
        }

        public BLL_Common(string connectionname)
        {
            _unitofwork = new UnitOfWork(connectionname);
             autoGenInfoServ = new BLL_AutoGeneratedInfo(connectionname);
        }
        public int GetDcumentId(string docname,int companyid)
        {
            return _unitofwork.AutoGeneratedInfoRepository.Get(a=>a.FormName==docname && a.CompanyId==companyid).FirstOrDefault().DocumentID;
        }

        public string GetDocumentNo(string formName, int locationID, string locationCode, int documentId, bool isTemporytNo,int companyid)
        {
            
          
            AutoGenerateInfo autoGenerateInfo;
            autoGenerateInfo = autoGenInfoServ.GetAutoGenerateInfoByForm(formName,companyid);
            string getNewCode = string.Empty;
            long tempCode = 0;

            string preFix = string.Empty;

            bool isLocationCode = autoGenerateInfo.IsLocationCode;
            int codeLength = autoGenerateInfo.CodeLength;


            if (string.IsNullOrEmpty(autoGenerateInfo.Prefix))
            {
                preFix = autoGenerateInfo.Prefix2.Trim();
            }
            else
            {
                preFix = autoGenerateInfo.Prefix.Trim();
            }

            if (isTemporytNo)
            {
                if ((preFix.StartsWith("T"))) { preFix = "X"; }
                else { preFix = "T"; }
            }

            if (isLocationCode) { preFix = preFix + locationCode.Trim() + autoGenerateInfo.Separator; }

            if (isTemporytNo)
            {


                //  context.DocumentNumber.Update(d=>d.LocationId==locationID && d.DocumentId==documentId,d=>new DocumentNumber{TempDocumentNo=d.TempDocumentNo+1});

                //no 
                //d => d.LocationId.Equals(locationID) && d.DocumentId.Equals(documentId),
                //d => new DocumentNumber { TempDocumentNo = d.TempDocumentNo + 1 }
                //);

                var existdocno = _unitofwork.DocumentNumberRepository.Get(d => d.LocationId == locationID && d.DocumentId == documentId).FirstOrDefault();
                existdocno.TempDocumentNo = existdocno.TempDocumentNo + 1;

                _unitofwork.DocumentNumberRepository.Update(existdocno);
                _unitofwork.Save();
                var dd = _unitofwork.DocumentNumberRepository.Get(d => d.LocationId.Equals(locationID) && d.DocumentId.Equals(documentId)).Max(d => d.TempDocumentNo);
                tempCode = _unitofwork.DocumentNumberRepository.Get(d => d.LocationId.Equals(locationID) && d.DocumentId.Equals(documentId)).Max(d => d.TempDocumentNo);
            }
            else
            {
                // context.DocumentNumber.Update(d => d.LocationId.Equals(locationID) && d.DocumentId.Equals(documentId), d => new DocumentNumber { DocumentNo = d.DocumentNo + 1 });
                var existdocno = _unitofwork.DocumentNumberRepository.Get(d => d.LocationId.Equals(locationID) && d.DocumentId.Equals(documentId)).FirstOrDefault();
                existdocno.DocumentNo = existdocno.DocumentNo + 1;

                _unitofwork.DocumentNumberRepository.Update(existdocno);
                _unitofwork.Save();

                tempCode = _unitofwork.DocumentNumberRepository.Get(d => d.LocationId.Equals(locationID) && d.DocumentId.Equals(documentId)).Max(d => d.DocumentNo);
            }

            getNewCode = (tempCode).ToString();

            getNewCode = preFix + new StringBuilder().Insert(0, "0", (codeLength - preFix.Length)) + getNewCode;
            return getNewCode.ToUpper();
        }

        public string GetDocumentTemporyNo(string formName, int locationID, string locationCode, int documentId, bool isTemporytNo,int companyid)
        {

           
            AutoGenerateInfo autoGenerateInfo;
            autoGenerateInfo = autoGenInfoServ.GetAutoGenerateInfoByForm(formName,companyid);
            string getNewCode = string.Empty;
            long tempCode = 0;

            string preFix = string.Empty;

            bool isLocationCode = autoGenerateInfo.IsLocationCode;
            int codeLength = autoGenerateInfo.CodeLength;


            if (string.IsNullOrEmpty(autoGenerateInfo.Prefix))
            {
                preFix = autoGenerateInfo.Prefix2.Trim();
            }
            else
            {
                preFix = autoGenerateInfo.Prefix.Trim();
            }

            if (isTemporytNo)
            {
                if ((preFix.StartsWith("T"))) { preFix = "X"; }
                else { preFix = "T"; }
            }
            locationCode = locationID.ToString();
            if (isLocationCode) { preFix = preFix + locationCode.Trim() + autoGenerateInfo.Separator; }

            if (isTemporytNo)
            {
                // var dd = _unitofwork.DocumentNumberRepository.Get(d => d.LocationId.Equals(locationID) && d.DocumentId.Equals(documentId)).Max(d => d.TempDocumentNo);
                tempCode = _unitofwork.DocumentNumberRepository.Get(d => d.LocationId.Equals(locationID) && d.DocumentId.Equals(documentId)).Max(d => d.TempDocumentNo);
            }
            getNewCode = (tempCode).ToString();

            getNewCode = preFix + new StringBuilder().Insert(0, "0", (codeLength - preFix.Length)) + getNewCode;
            return getNewCode.ToUpper();
        }

        public string GetDocumentNumber(string formName, int locationID, string locationCode, int documentId,int companyid)
        {
          
            AutoGenerateInfo autoGenerateInfo;
            autoGenerateInfo = autoGenInfoServ.GetAutoGenerateInfoByForm(formName,companyid);
            string getNewCode = string.Empty;
            long tempCode = 0;

            string preFix = string.Empty;

            bool isLocationCode = autoGenerateInfo.IsLocationCode;
            int codeLength = autoGenerateInfo.CodeLength;

            if (string.IsNullOrEmpty(autoGenerateInfo.Prefix))
            {
                preFix = autoGenerateInfo.Prefix2.Trim();
            }
            else
            {
                preFix = autoGenerateInfo.Prefix.Trim();
            }
            locationCode = locationID.ToString();
            if (isLocationCode) { preFix = preFix + locationCode.Trim() + autoGenerateInfo.Separator; }

            tempCode = _unitofwork.DocumentNumberRepository.Get(d => d.LocationId.Equals(locationID) && d.DocumentId.Equals(documentId)).Max(d => d.DocumentNo);
            //if (tempCode == 0) { tempCode = 1; }
           // if(tempCode== null )
            getNewCode = (tempCode+1).ToString();
            
            getNewCode = preFix + new StringBuilder().Insert(0, "0", (codeLength - preFix.Length)) + getNewCode;
            return getNewCode.ToUpper();
        }

        public SysConfiguration GetConfigurations()
        {
            return _unitofwork.SysConfigurationRepository.Get().FirstOrDefault();
        }
    }
}