using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using HospitalityManagement.Models;

namespace HospitalityManagement.Service
{
    public class AutoGeneratedInfoService
    {
        ApplicationDbContext context = new ApplicationDbContext();

        public  AutoGenerateInfo GetAutoGenerateInfoByForm(string formName)
        {
            AutoGenerateInfo autoGenerateInfo = new AutoGenerateInfo();
            try
            {
                if (context.AutoGenerateInfo.FirstOrDefault(ai => ai.FormName == formName) != null)
                {
                    autoGenerateInfo = context.AutoGenerateInfo.FirstOrDefault(ai => ai.FormName == formName);
                }

                if (string.IsNullOrEmpty(autoGenerateInfo.FormText))
                {
                    autoGenerateInfo.FormText = "Select a Caption";
                }

            }
            catch (Exception ex)
            {
                throw;
            }
            return autoGenerateInfo;
        }
    }
}