using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Text;
using System.Web;
using HospitalityManagement.Models;
//using MoreLinq;
using EntityFramework.Extensions;

namespace HospitalityManagement.Service
{
    public class CommonService
    {
        ApplicationDbContext context = new ApplicationDbContext();

        public int GetDcumentId(string docname)
        {
            return context.AutoGenerateInfo.Where(a=>a.FormName==docname).FirstOrDefault().DocumentID;
        }

        public string GetDocumentNo(string formName, int locationID, string locationCode, int documentId, bool isTemporytNo)
        {
            
            AutoGeneratedInfoService autoGenInfoServ = new AutoGeneratedInfoService();
            AutoGenerateInfo autoGenerateInfo;
            autoGenerateInfo = autoGenInfoServ.GetAutoGenerateInfoByForm(formName);
            string getNewCode = string.Empty;
            long tempCode = 0;

            string preFix = string.Empty;

            bool isLocationCode = autoGenerateInfo.IsLocationCode;
            int codeLength = autoGenerateInfo.CodeLength;


            if (string.IsNullOrEmpty(autoGenerateInfo.Prefix))
            {
                preFix = autoGenerateInfo.Prefix2.Trim();
            }
            else
            {
                preFix = autoGenerateInfo.Prefix.Trim();
            }

            if (isTemporytNo)
            {
                if ((preFix.StartsWith("T"))) { preFix = "X"; }
                else { preFix = "T"; }
            }

            if (isLocationCode) { preFix = preFix + locationCode.Trim(); }

            if (isTemporytNo)
            {

               
               context.DocumentNumber.Update(d=>d.LocationId==locationID && d.DocumentId==documentId,d=>new DocumentNumber{TempDocumentNo=d.TempDocumentNo+1});

                    //d => d.LocationId.Equals(locationID) && d.DocumentId.Equals(documentId),
                    //d => new DocumentNumber { TempDocumentNo = d.TempDocumentNo + 1 }
                    //);

                var dd = context.DocumentNumber.Where(d => d.LocationId.Equals(locationID) && d.DocumentId.Equals(documentId)).Max(d => d.TempDocumentNo);

                tempCode = context.DocumentNumber.Where(d => d.LocationId.Equals(locationID) && d.DocumentId.Equals(documentId)).Max(d => d.TempDocumentNo);
            }
            else
            {
                context.DocumentNumber.Update(d => d.LocationId.Equals(locationID) && d.DocumentId.Equals(documentId), d => new DocumentNumber { DocumentNo = d.DocumentNo + 1 });

                tempCode = context.DocumentNumber.Where(d => d.LocationId.Equals(locationID) && d.DocumentId.Equals(documentId)).Max(d => d.DocumentNo);
            }

            getNewCode = (tempCode).ToString();

            getNewCode = preFix + new StringBuilder().Insert(0, "0", (codeLength - preFix.Length)) + getNewCode;
            return getNewCode.ToUpper();
        }


        public SysConfiguration GetConfigurations()
        {
            return context.SysConfiguration.FirstOrDefault();
        }

    }
}