// <auto-generated />
namespace HospitalityManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class hasanka056 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hasanka056));
        
        string IMigrationMetadata.Id
        {
            get { return "201808270631276_hasanka 056"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
