// <auto-generated />
namespace HospitalityManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class hasanka146 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hasanka146));
        
        string IMigrationMetadata.Id
        {
            get { return "201901071112055_hasanka 146"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
