namespace HospitalityManagement.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class _189 : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.PaymentDets",
                c => new
                    {
                        PaymentDetID = c.Int(nullable: false, identity: true),
                        RowNo = c.Int(nullable: false),
                        PayTypeID = c.Int(nullable: false),
                        Amount = c.Decimal(nullable: false, precision: 18, scale: 2),
                        Balance = c.Decimal(nullable: false, precision: 18, scale: 2),
                        SDate = c.DateTime(nullable: false),
                        Receipt = c.String(),
                        LocationID = c.Int(nullable: false),
                        CashierID = c.Int(nullable: false),
                        UnitNo = c.Int(nullable: false),
                        BillTypeID = c.Int(nullable: false),
                        SaleTypeID = c.Int(nullable: false),
                        RefNo = c.String(),
                        BankId = c.Int(nullable: false),
                        ChequeDate = c.DateTime(nullable: false),
                        IsRecallAdv = c.Int(nullable: false),
                        RecallNo = c.String(),
                        Descrip = c.String(),
                        EnCodeName = c.String(),
                        UpdatedBy = c.Int(nullable: false),
                        Status = c.Int(nullable: false),
                        ZNo = c.Int(nullable: false),
                        CustomerId = c.Int(nullable: false),
                        CustomerType = c.Int(nullable: false),
                        CustomerCode = c.String(),
                        GroupOfCompanyID = c.Int(nullable: false),
                        Datatransfer = c.Int(nullable: false),
                        ZDate = c.DateTime(nullable: false),
                        TerminalID = c.Int(nullable: false),
                        LoyaltyType = c.Int(nullable: false),
                        IsUploadToGL = c.Int(nullable: false),
                        LocationIDBilling = c.Int(nullable: false),
                        TableID = c.Int(nullable: false),
                        TicketID = c.Int(nullable: false),
                        OrderNo = c.Int(nullable: false),
                        ShiftNo = c.Int(nullable: false),
                        IsDayEnd = c.Boolean(nullable: false),
                        UpdateUnitNo = c.Int(nullable: false),
                        Online = c.Int(nullable: false),
                        SerialNo = c.String(),
                        CurrencyCode = c.String(),
                        CurrencyRate = c.Decimal(nullable: false, precision: 18, scale: 2),
                        AcountNumber = c.String(),
                        CopperratePrice = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IsCopperratePriceEnable = c.Boolean(nullable: false),
                        AmountCopperratePrice = c.Decimal(nullable: false, precision: 18, scale: 2),
                        BalanceCopperratePrice = c.Decimal(nullable: false, precision: 18, scale: 2),
                    })
                .PrimaryKey(t => t.PaymentDetID);
            
            CreateTable(
                "dbo.SuspendDets",
                c => new
                    {
                        Idx = c.Int(nullable: false, identity: true),
                        ProductID = c.Int(nullable: false),
                        ProductCode = c.String(maxLength: 25),
                        RefCode = c.String(maxLength: 25),
                        BarCodeFull = c.Long(nullable: false),
                        Descrip = c.String(maxLength: 50),
                        BatchNo = c.String(maxLength: 50),
                        SerialNo = c.String(maxLength: 50),
                        ExpiaryDate = c.DateTime(nullable: false),
                        Cost = c.Decimal(nullable: false, precision: 18, scale: 2),
                        AvgCost = c.Decimal(nullable: false, precision: 18, scale: 2),
                        Qty = c.Decimal(nullable: false, precision: 18, scale: 2),
                        Amount = c.Decimal(nullable: false, precision: 18, scale: 2),
                        UnitOfMeasureID = c.Int(nullable: false),
                        UnitOfMeasureName = c.String(maxLength: 10),
                        ConvertFactor = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IDI1 = c.Int(nullable: false),
                        IDis1 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IDiscount1 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IDI1CashierID = c.Int(nullable: false),
                        IDI2 = c.Int(nullable: false),
                        IDis2 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IDiscount2 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IDI2CashierID = c.Int(nullable: false),
                        IDI3 = c.Int(nullable: false),
                        IDis3 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IDiscount3 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IDI3CashierID = c.Int(nullable: false),
                        IDI4 = c.Int(nullable: false),
                        IDis4 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IDiscount4 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IDI4CashierID = c.Int(nullable: false),
                        IDI5 = c.Int(nullable: false),
                        IDis5 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IDiscount5 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IDI5CashierID = c.Int(nullable: false),
                        Rate = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IsSDis = c.Boolean(nullable: false),
                        SDNo = c.Int(nullable: false),
                        SDID = c.Int(nullable: false),
                        SDIs = c.Decimal(nullable: false, precision: 18, scale: 2),
                        SDiscount = c.Decimal(nullable: false, precision: 18, scale: 2),
                        DDisCashierID = c.Int(nullable: false),
                        Nett = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LocationID = c.Int(nullable: false),
                        DocumentID = c.Int(nullable: false),
                        BillTypeID = c.Int(nullable: false),
                        SaleTypeID = c.Int(nullable: false),
                        Receipt = c.String(maxLength: 10),
                        SalesmanID = c.Int(nullable: false),
                        Salesman = c.String(maxLength: 15),
                        CustomerID = c.Int(nullable: false),
                        Customer = c.String(maxLength: 15),
                        CashierID = c.Int(nullable: false),
                        Cashier = c.String(maxLength: 15),
                        StartTime = c.DateTime(nullable: false),
                        EndTime = c.DateTime(nullable: false),
                        RecDate = c.DateTime(nullable: false),
                        BaseUnitID = c.Int(nullable: false),
                        UnitNo = c.Int(nullable: false),
                        RowNo = c.Int(nullable: false),
                        IsRecall = c.Boolean(nullable: false),
                        RecallNo = c.String(maxLength: 10),
                        RecallAdv = c.Boolean(nullable: false),
                        TaxAmount = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IsTax = c.Boolean(nullable: false),
                        TaxPercentage = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IsStock = c.Boolean(nullable: false),
                        SuspendNo = c.String(maxLength: 50),
                        SuspendBy = c.Int(nullable: false),
                        CustomerType = c.Int(nullable: false),
                        TransStatus = c.Int(nullable: false),
                        IsPromotionApplied = c.Boolean(nullable: false),
                        PromotionID = c.Int(nullable: false),
                        IsPromotion = c.Boolean(nullable: false),
                        InvPriceLevelID = c.Int(nullable: false),
                        ItemSerial = c.String(maxLength: 50),
                        warranty = c.String(maxLength: 50),
                        TableNumber = c.Int(nullable: false),
                        PrinterType = c.Int(nullable: false),
                        IsPritRpt = c.Boolean(nullable: false),
                        ReferenceProductId = c.Int(nullable: false),
                        ReferenceProductRow = c.Int(nullable: false),
                        IsAddonItem = c.Boolean(nullable: false),
                        IsTaxEnable = c.Boolean(nullable: false),
                        TaxCode = c.String(maxLength: 50),
                        SplitItemReceiptNo = c.String(maxLength: 50),
                        Price = c.Decimal(nullable: false, precision: 18, scale: 2),
                    })
                .PrimaryKey(t => t.Idx);
            
            CreateTable(
                "dbo.SuspendDetBackups",
                c => new
                    {
                        Idx = c.Int(nullable: false, identity: true),
                        ProductID = c.Int(nullable: false),
                        ProductCode = c.String(),
                        RefCode = c.String(),
                        BarCodeFull = c.Int(nullable: false),
                        Descrip = c.String(),
                        BatchNo = c.String(),
                        SerialNo = c.String(),
                        ExpiaryDate = c.DateTime(nullable: false),
                        Cost = c.Decimal(nullable: false, precision: 18, scale: 2),
                        AvgCost = c.Decimal(nullable: false, precision: 18, scale: 2),
                        Price = c.Decimal(nullable: false, precision: 18, scale: 2),
                        Qty = c.Decimal(nullable: false, precision: 18, scale: 2),
                        Amount = c.Decimal(nullable: false, precision: 18, scale: 2),
                        UnitOfMeasureID = c.Int(nullable: false),
                        UnitOfMeasureName = c.String(),
                        ConvertFactor = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IDI1 = c.Int(nullable: false),
                        IDis1 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IDiscount1 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IDI1CashierID = c.Int(nullable: false),
                        IDI2 = c.Int(nullable: false),
                        IDis2 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IDiscount2 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IDI2CashierID = c.Int(nullable: false),
                        IDI3 = c.Int(nullable: false),
                        IDis3 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IDiscount3 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IDI3CashierID = c.Int(nullable: false),
                        IDI4 = c.Int(nullable: false),
                        IDis4 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IDiscount4 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IDI4CashierID = c.Int(nullable: false),
                        IDI5 = c.Int(nullable: false),
                        IDis5 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IDiscount5 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IDI5CashierID = c.Int(nullable: false),
                        Rate = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IsSDis = c.Boolean(nullable: false),
                        SDNo = c.Int(nullable: false),
                        SDID = c.Int(nullable: false),
                        SDIs = c.Decimal(nullable: false, precision: 18, scale: 2),
                        SDiscount = c.Decimal(nullable: false, precision: 18, scale: 2),
                        DDisCashierID = c.Int(nullable: false),
                        Nett = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LocationID = c.Int(nullable: false),
                        DocumentID = c.Int(nullable: false),
                        BillTypeID = c.Int(nullable: false),
                        SaleTypeID = c.Int(nullable: false),
                        Receipt = c.String(),
                        SalesmanID = c.Int(nullable: false),
                        Salesman = c.String(),
                        CustomerID = c.Int(nullable: false),
                        Customer = c.String(),
                        CashierID = c.Int(nullable: false),
                        Cashier = c.String(),
                        StartTime = c.DateTime(nullable: false),
                        EndTime = c.DateTime(nullable: false),
                        RecDate = c.DateTime(nullable: false),
                        BaseUnitID = c.Int(nullable: false),
                        UnitNo = c.Int(nullable: false),
                        RowNo = c.Int(nullable: false),
                        IsRecall = c.Boolean(nullable: false),
                        RecallNo = c.String(),
                        RecallAdv = c.Boolean(nullable: false),
                        TaxAmount = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IsTax = c.Boolean(nullable: false),
                        TaxPercentage = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IsStock = c.Boolean(nullable: false),
                        SuspendNo = c.String(),
                        SuspendBy = c.Int(nullable: false),
                        CustomerType = c.Int(nullable: false),
                        TransStatus = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.Idx);
            
            CreateTable(
                "dbo.SuspendHeds",
                c => new
                    {
                        Idx = c.Int(nullable: false, identity: true),
                        SuspendNo = c.String(maxLength: 50),
                        Receipt = c.String(maxLength: 50),
                        LocationID = c.Int(nullable: false),
                        UnitNo = c.Int(nullable: false),
                        STime = c.DateTime(nullable: false),
                        SDate = c.DateTime(nullable: false),
                        Amount = c.Decimal(nullable: false, precision: 18, scale: 2),
                        CashierID = c.Int(nullable: false),
                        IsRecall = c.Boolean(nullable: false),
                        RecallReceipt = c.String(maxLength: 50),
                        RecallCashierID = c.Int(nullable: false),
                        RecallCashier = c.String(maxLength: 20),
                        RecallUnitNo = c.Int(nullable: false),
                        RecallTime = c.DateTime(nullable: false),
                        TransStatus = c.Int(nullable: false),
                        TokenNumber = c.String(maxLength: 50),
                        NextBillDate = c.Int(nullable: false),
                        CustomerId = c.Int(nullable: false),
                        TableNumber = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.Idx);
            
            CreateTable(
                "dbo.SuspendHedBackups",
                c => new
                    {
                        Idx = c.Int(nullable: false, identity: true),
                        SuspendNo = c.String(),
                        Receipt = c.String(),
                        LocationID = c.Int(nullable: false),
                        UnitNo = c.Int(nullable: false),
                        STime = c.DateTime(nullable: false),
                        SDate = c.DateTime(nullable: false),
                        Amount = c.Decimal(nullable: false, precision: 18, scale: 2),
                        CashierID = c.Int(nullable: false),
                        IsRecall = c.Boolean(nullable: false),
                        RecallReceipt = c.String(),
                        RecallCashierID = c.Int(nullable: false),
                        RecallCashier = c.String(),
                        RecallUnitNo = c.Int(nullable: false),
                        TransStatus = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.Idx);
            
            CreateTable(
                "dbo.SuspendPaymentDets",
                c => new
                    {
                        Idx = c.Int(nullable: false, identity: true),
                        RowNo = c.Int(nullable: false),
                        PayTypeID = c.Int(nullable: false),
                        Amount = c.Decimal(nullable: false, precision: 18, scale: 2),
                        Balance = c.Decimal(nullable: false, precision: 18, scale: 2),
                        SDate = c.DateTime(nullable: false),
                        Receipt = c.String(),
                        LocationID = c.Int(nullable: false),
                        CashierID = c.Int(nullable: false),
                        UnitNo = c.Int(nullable: false),
                        BillTypeID = c.Int(nullable: false),
                        RefNo = c.String(),
                        BankId = c.Int(nullable: false),
                        ChequeDate = c.DateTime(nullable: false),
                        IsRecallAdv = c.Boolean(nullable: false),
                        RecallNo = c.String(),
                        Descrip = c.String(),
                        EnCodeName = c.String(),
                        SuspendNo = c.String(),
                        SuspendBy = c.Int(nullable: false),
                        IsDeleteOnRecall = c.Boolean(nullable: false),
                    })
                .PrimaryKey(t => t.Idx);
            
            CreateTable(
                "dbo.TransactionDets",
                c => new
                    {
                        TransactionDetID = c.Int(nullable: false, identity: true),
                        ProductID = c.Int(nullable: false),
                        ProductCode = c.String(),
                        RefCode = c.String(),
                        BarCodeFull = c.Int(nullable: false),
                        Descrip = c.String(),
                        BatchNo = c.String(),
                        SerialNo = c.String(),
                        ExpiryDate = c.DateTime(nullable: false),
                        Cost = c.Decimal(nullable: false, precision: 18, scale: 2),
                        AvgCost = c.Decimal(nullable: false, precision: 18, scale: 2),
                        Price = c.Decimal(nullable: false, precision: 18, scale: 2),
                        Qty = c.Decimal(nullable: false, precision: 18, scale: 2),
                        BalanceQty = c.Decimal(nullable: false, precision: 18, scale: 2),
                        Amount = c.Decimal(nullable: false, precision: 18, scale: 2),
                        UnitOfMeasureID = c.Int(nullable: false),
                        UnitOfMeasureName = c.String(),
                        ConvertFactor = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IDI1 = c.Int(nullable: false),
                        IDis1 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IDiscount1 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IDI1CashierID = c.Int(nullable: false),
                        IDI2 = c.Int(nullable: false),
                        IDis2 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IDiscount2 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IDI2CashierID = c.Int(nullable: false),
                        IDI3 = c.Int(nullable: false),
                        IDis3 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IDiscount3 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IDI3CashierID = c.Int(nullable: false),
                        IDI4 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IDis4 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IDiscount4 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IDI4CashierID = c.Int(nullable: false),
                        IDI5 = c.Int(nullable: false),
                        IDis5 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IDiscount5 = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IDI5CashierID = c.Int(nullable: false),
                        Rate = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IsSDis = c.Boolean(nullable: false),
                        SDNo = c.Int(nullable: false),
                        SDID = c.Int(nullable: false),
                        SDIs = c.Decimal(nullable: false, precision: 18, scale: 2),
                        SDiscount = c.Decimal(nullable: false, precision: 18, scale: 2),
                        DDisCashierID = c.Int(nullable: false),
                        Nett = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LocationID = c.Int(nullable: false),
                        DocumentID = c.Int(nullable: false),
                        BillTypeID = c.Int(nullable: false),
                        SaleTypeID = c.Int(nullable: false),
                        Receipt = c.String(),
                        SalesmanID = c.Int(nullable: false),
                        Salesman = c.String(),
                        CustomerID = c.Int(nullable: false),
                        Customer = c.String(),
                        CashierID = c.Int(nullable: false),
                        Cashier = c.String(),
                        StartTime = c.DateTime(nullable: false),
                        EndTime = c.DateTime(nullable: false),
                        RecDate = c.DateTime(nullable: false),
                        BaseUnitID = c.Int(nullable: false),
                        UnitNo = c.Int(nullable: false),
                        RowNo = c.Int(nullable: false),
                        IsRecall = c.Boolean(nullable: false),
                        RecallNO = c.String(),
                        RecallAdv = c.Boolean(nullable: false),
                        TaxAmount = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IsTax = c.Boolean(nullable: false),
                        TaxPercentage = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IsStock = c.Boolean(nullable: false),
                        UpdateBy = c.Int(nullable: false),
                        Status = c.Int(nullable: false),
                        ZNo = c.Int(nullable: false),
                        GroupOfCompanyID = c.Int(nullable: false),
                        DataTransfer = c.Int(nullable: false),
                        CustomerType = c.Int(nullable: false),
                        TransStatus = c.Int(nullable: false),
                        ZDate = c.DateTime(nullable: false),
                        IsPromotionApplied = c.Int(nullable: false),
                        PromotionID = c.Int(nullable: false),
                        IsPromotion = c.Int(nullable: false),
                        LocationIDBilling = c.Int(nullable: false),
                        TableID = c.Int(nullable: false),
                        OrderTerminalID = c.Int(nullable: false),
                        TicketID = c.Int(nullable: false),
                        OrderNo = c.Int(nullable: false),
                        IsPrinted = c.Int(nullable: false),
                        ItemComment = c.String(),
                        Packs = c.Int(nullable: false),
                        IsCancelKOT = c.Boolean(nullable: false),
                        StewardID = c.Int(nullable: false),
                        StewardName = c.String(),
                        ServiceCharge = c.Decimal(nullable: false, precision: 18, scale: 2),
                        ServiceChargeAmount = c.Decimal(nullable: false, precision: 18, scale: 2),
                        ShiftNo = c.Int(nullable: false),
                        IsDayEnd = c.Boolean(nullable: false),
                        UpdateUnitNo = c.Int(nullable: false),
                        InvPriceLevelID = c.Int(nullable: false),
                        Online = c.Int(nullable: false),
                        Deliverdate = c.DateTime(nullable: false),
                        PackSize = c.Decimal(nullable: false, precision: 18, scale: 2),
                        TourAgentCode = c.String(),
                        TourAgentId = c.Int(nullable: false),
                        TourAmount = c.Decimal(nullable: false, precision: 18, scale: 2),
                        TourPrecent = c.Decimal(nullable: false, precision: 18, scale: 2),
                        TourCommition = c.Decimal(nullable: false, precision: 18, scale: 2),
                        TourCommitionPaidAmount = c.Decimal(nullable: false, precision: 18, scale: 2),
                        TourAgentCompanyCode = c.String(),
                        TourAgentCompanyId = c.Int(nullable: false),
                        TourCompanyAmount = c.Decimal(nullable: false, precision: 18, scale: 2),
                        TourCompanyPrecent = c.Decimal(nullable: false, precision: 18, scale: 2),
                        TourCompanyCommition = c.Decimal(nullable: false, precision: 18, scale: 2),
                        TourCompanyCommitionPaidAmount = c.Decimal(nullable: false, precision: 18, scale: 2),
                        DelvryBalQty = c.Decimal(nullable: false, precision: 18, scale: 2),
                        warranty = c.Decimal(nullable: false, precision: 18, scale: 2),
                        ItemSerial = c.String(),
                        CreditPeriod = c.Int(nullable: false),
                        CopperratePrice = c.Decimal(nullable: false, precision: 18, scale: 2),
                        SellingCopperratePrice = c.Decimal(nullable: false, precision: 18, scale: 2),
                        AmountCopperratePrice = c.Decimal(nullable: false, precision: 18, scale: 2),
                        NettCopperratePrice = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IsCopperratePriceEnable = c.Boolean(nullable: false),
                        RateCopperratePrice = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IsBundleItem = c.Boolean(nullable: false),
                        NextBillDate = c.Int(nullable: false),
                        PackPrice = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IsPackSale = c.Boolean(nullable: false),
                        ExchageQty = c.Decimal(nullable: false, precision: 18, scale: 2),
                    })
                .PrimaryKey(t => t.TransactionDetID);
            
            CreateTable(
                "dbo.TransactionLogs",
                c => new
                    {
                        TransactionLogID = c.Int(nullable: false, identity: true),
                        TransactionDocumentNo = c.String(),
                        TransactionDocumentId = c.Int(nullable: false),
                        FormName = c.String(),
                        TransactionDate = c.DateTime(nullable: false),
                        AuditDate = c.DateTime(nullable: false),
                        LoggedLocation = c.String(),
                        ReferenceNo = c.String(),
                        ComputerName = c.String(),
                        GroupOfCompanyID = c.Int(nullable: false),
                        CreatedUser = c.String(),
                        CreatedDate = c.DateTime(nullable: false),
                        ModifiedUser = c.String(),
                        ModifiedDate = c.DateTime(nullable: false),
                        DataTransfer = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.TransactionLogID);
            
        }
        
        public override void Down()
        {
            DropTable("dbo.TransactionLogs");
            DropTable("dbo.TransactionDets");
            DropTable("dbo.SuspendPaymentDets");
            DropTable("dbo.SuspendHedBackups");
            DropTable("dbo.SuspendHeds");
            DropTable("dbo.SuspendDetBackups");
            DropTable("dbo.SuspendDets");
            DropTable("dbo.PaymentDets");
        }
    }
}
