namespace HospitalityManagement.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class _89 : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.LOGAddons",
                c => new
                    {
                        LOGAddonsId = c.Int(nullable: false, identity: true),
                        ProductId = c.Long(nullable: false),
                        ProductAddonId = c.Long(nullable: false),
                        DepartmentId = c.Long(nullable: false),
                        IsActive = c.Boolean(nullable: false),
                        AddonSellingPrice = c.Decimal(nullable: false, precision: 18, scale: 2),
                        AddonQuantity = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IsShowOnBill = c.Boolean(nullable: false),
                        GroupOfCompanyID = c.Int(nullable: false),
                        CompanyID = c.Int(nullable: false),
                        LocationId = c.Int(nullable: false),
                        CreatedUser = c.String(maxLength: 50),
                        CreatedDate = c.DateTime(nullable: false),
                        ModifiedUser = c.String(maxLength: 50),
                        ModifiedDate = c.DateTime(nullable: false),
                        DataTransfer = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.LOGAddonsId);
            
            CreateTable(
                "dbo.LOGCustomers",
                c => new
                    {
                        CustomerID = c.Int(nullable: false, identity: true),
                        CustomerCode = c.String(nullable: false),
                        CustomerTitle = c.String(nullable: false),
                        CustomerName = c.String(nullable: false, maxLength: 100),
                        CustomerType = c.String(),
                        CustomerCategoryId = c.Int(nullable: false),
                        BillingAddress1 = c.String(nullable: false, maxLength: 100),
                        BillingAddress2 = c.String(nullable: false, maxLength: 100),
                        BillingAddress3 = c.String(),
                        DOB = c.DateTime(),
                        NIC = c.String(nullable: false, maxLength: 12),
                        Passport = c.String(),
                        Telephone = c.String(),
                        Mobile = c.String(nullable: false),
                        Fax = c.String(),
                        Email = c.String(),
                        VehicleNo = c.String(),
                        Profession = c.String(),
                        WeddingAnniversary = c.DateTime(),
                        IsActiveForLoyalty = c.Boolean(nullable: false),
                        CustomerPicture = c.Binary(),
                        CustomerPictureName = c.String(),
                        CustomerPictureType = c.String(),
                        IsActive = c.Boolean(nullable: false),
                        IsDelete = c.Boolean(nullable: false),
                        CreditLimit = c.Decimal(nullable: false, precision: 18, scale: 2),
                        Outstanding = c.Decimal(nullable: false, precision: 18, scale: 2),
                        EPFNo = c.String(maxLength: 50, unicode: false),
                        MembershipCardNo = c.String(maxLength: 50, unicode: false),
                        Other = c.String(maxLength: 50, unicode: false),
                        Remarks = c.String(maxLength: 200, unicode: false),
                        CustomerStatus = c.String(maxLength: 20, unicode: false),
                        GroupOfCompanyID = c.Int(nullable: false),
                        CompanyID = c.Int(nullable: false),
                        LocationId = c.Int(nullable: false),
                        CreatedUser = c.String(maxLength: 50),
                        CreatedDate = c.DateTime(nullable: false),
                        ModifiedUser = c.String(maxLength: 50),
                        ModifiedDate = c.DateTime(nullable: false),
                        DataTransfer = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.CustomerID);
            
            CreateTable(
                "dbo.LOGInvPromotionMasters",
                c => new
                    {
                        InvPromotionMasterID = c.Long(nullable: false, identity: true),
                        CompanyID = c.Int(nullable: false),
                        LocationID = c.Int(nullable: false),
                        CostCentreID = c.Int(nullable: false),
                        PromotionCode = c.String(nullable: false, maxLength: 15),
                        PromotionName = c.String(nullable: false, maxLength: 50),
                        IsAutoApply = c.Boolean(nullable: false),
                        PromotionTypeID = c.Int(nullable: false),
                        StartDate = c.DateTime(nullable: false),
                        EndDate = c.DateTime(nullable: false),
                        IsMonday = c.Boolean(nullable: false),
                        IsTuesday = c.Boolean(nullable: false),
                        IsWednesday = c.Boolean(nullable: false),
                        IsThuresday = c.Boolean(nullable: false),
                        IsFriday = c.Boolean(nullable: false),
                        IsSaturday = c.Boolean(nullable: false),
                        IsSunday = c.Boolean(nullable: false),
                        IsMondayTime = c.Boolean(nullable: false),
                        IsTuesdayTime = c.Boolean(nullable: false),
                        IsWednesdayTime = c.Boolean(nullable: false),
                        IsThuresdayTime = c.Boolean(nullable: false),
                        IsFridayTime = c.Boolean(nullable: false),
                        IsSaturdayTime = c.Boolean(nullable: false),
                        IsSundayTime = c.Boolean(nullable: false),
                        MondayStartTime = c.DateTime(),
                        MondayEndTime = c.DateTime(),
                        TuesdayStartTime = c.DateTime(),
                        TuesdayEndTime = c.DateTime(),
                        WednesdayStartTime = c.DateTime(),
                        WednesdayEndTime = c.DateTime(),
                        ThuresdayStartTime = c.DateTime(),
                        ThuresdayEndTime = c.DateTime(),
                        FridayStartTime = c.DateTime(),
                        FridayEndTime = c.DateTime(),
                        SaturdayStartTime = c.DateTime(),
                        SaturdayEndTime = c.DateTime(),
                        SundayStartTime = c.DateTime(),
                        SundayEndTime = c.DateTime(),
                        PaymentMethodID = c.Int(nullable: false),
                        IsProvider = c.Boolean(nullable: false),
                        IsAllLocations = c.Boolean(nullable: false),
                        IsAllType = c.Boolean(nullable: false),
                        IsValueRange = c.Boolean(nullable: false),
                        MinimumValue = c.Decimal(nullable: false, precision: 18, scale: 2),
                        MaximumValue = c.Decimal(nullable: false, precision: 18, scale: 2),
                        DiscountValue = c.Decimal(nullable: false, precision: 18, scale: 2),
                        DiscountPercentage = c.Decimal(nullable: false, precision: 18, scale: 2),
                        Points = c.Decimal(nullable: false, precision: 18, scale: 2),
                        Remark = c.String(maxLength: 150),
                        DisplayMessage = c.String(maxLength: 150),
                        CashierMessage = c.String(maxLength: 150),
                        IsDelete = c.Boolean(nullable: false),
                        IsRaffle = c.Boolean(nullable: false),
                        IsIncreseQty = c.Boolean(nullable: false),
                        PromotionTypeNew = c.Int(nullable: false),
                        SupplierID = c.Int(nullable: false),
                        ModifiedDate = c.DateTime(nullable: false),
                        PromotionCount = c.Int(nullable: false),
                        CustomerGroupId = c.Int(),
                    })
                .PrimaryKey(t => t.InvPromotionMasterID);
            
            CreateTable(
                "dbo.LOGProducts",
                c => new
                    {
                        ProductId = c.Int(nullable: false, identity: true),
                        ProductCode = c.String(nullable: false, maxLength: 10),
                        ProductName = c.String(nullable: false, maxLength: 100),
                        NameOnInvoice = c.String(maxLength: 50),
                        IsPackItem = c.Boolean(nullable: false),
                        PackSize = c.Decimal(nullable: false, precision: 18, scale: 2),
                        PackPrice = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IsPromotion = c.Boolean(nullable: false),
                        IsFreeIssue = c.Boolean(nullable: false),
                        IsExpiry = c.Boolean(nullable: false),
                        IsTaxInclude = c.Boolean(nullable: false),
                        IsTax = c.Boolean(nullable: false),
                        WeightPerUnit = c.Int(nullable: false),
                        IsUnderCost = c.Boolean(nullable: false),
                        IsBundle = c.Boolean(nullable: false),
                        MaxPrice = c.Decimal(nullable: false, precision: 18, scale: 2),
                        MinPrice = c.Decimal(nullable: false, precision: 18, scale: 2),
                        DiscountPrecentage = c.Decimal(nullable: false, precision: 18, scale: 2),
                        MaximumDiscount = c.Decimal(nullable: false, precision: 18, scale: 2),
                        FixedDiscountPercentage = c.Decimal(nullable: false, precision: 18, scale: 2),
                        FixedDiscountAmount = c.Decimal(nullable: false, precision: 18, scale: 2),
                        MaximumDiscountPercentage = c.Decimal(nullable: false, precision: 18, scale: 2),
                        ProductNameInSinhala = c.String(maxLength: 100),
                        IsRowMaterial = c.Boolean(nullable: false),
                        IsAddon = c.Boolean(nullable: false),
                        IsCountable = c.Boolean(nullable: false),
                        IsDiscount = c.Boolean(nullable: false),
                        IsCostOnReceipe = c.Boolean(nullable: false),
                        IsScaleItem = c.Boolean(nullable: false),
                        IsActive = c.Boolean(nullable: false),
                        IsDelete = c.Boolean(nullable: false),
                        ProductImage = c.Binary(),
                        ProductImageName = c.String(),
                        ProductImageType = c.String(),
                        DepartmentId = c.Int(nullable: false),
                        CategoryId = c.Int(nullable: false),
                        SubCategoryId = c.Int(nullable: false),
                        CostPrice = c.Decimal(nullable: false, precision: 18, scale: 2),
                        SellingPrice = c.Decimal(nullable: false, precision: 18, scale: 2),
                        ReOrderLevel = c.Decimal(nullable: false, precision: 18, scale: 2),
                        ReOrderQuantity = c.Decimal(nullable: false, precision: 18, scale: 2),
                        LocationWiseStock = c.Decimal(nullable: false, precision: 18, scale: 2),
                        WastagePrc = c.Decimal(nullable: false, precision: 18, scale: 2),
                        PurchasingUnit = c.Int(nullable: false),
                        Printer = c.String(maxLength: 10),
                        Barcode = c.String(maxLength: 200),
                        IsItemLock = c.Boolean(nullable: false),
                        RefCode01 = c.String(maxLength: 200),
                        RefCode02 = c.String(maxLength: 200),
                        PrinterTypeId = c.Int(nullable: false),
                        AddonCategoryMasterId = c.Long(),
                        IsOpenItem = c.Boolean(nullable: false),
                        AutoProduction = c.Boolean(nullable: false),
                        GroupOfCompanyID = c.Int(nullable: false),
                        CompanyID = c.Int(nullable: false),
                        LocationId = c.Int(nullable: false),
                        CreatedUser = c.String(maxLength: 50),
                        CreatedDate = c.DateTime(nullable: false),
                        ModifiedUser = c.String(maxLength: 50),
                        ModifiedDate = c.DateTime(nullable: false),
                        DataTransfer = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.ProductId);
            
            CreateTable(
                "dbo.LOGProductServingUnits",
                c => new
                    {
                        ProductServingUnitId = c.Long(nullable: false, identity: true),
                        ProductId = c.Long(nullable: false),
                        ServingUnit = c.String(nullable: false),
                        CostPrice = c.Decimal(nullable: false, precision: 18, scale: 2),
                        SellingPrice = c.Decimal(nullable: false, precision: 18, scale: 2),
                        DeductStockOnRecipe = c.Boolean(nullable: false),
                        GroupOfCompanyID = c.Int(nullable: false),
                        CompanyID = c.Int(nullable: false),
                        LocationId = c.Int(nullable: false),
                        CreatedUser = c.String(maxLength: 50),
                        CreatedDate = c.DateTime(nullable: false),
                        ModifiedUser = c.String(maxLength: 50),
                        ModifiedDate = c.DateTime(nullable: false),
                        DataTransfer = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.ProductServingUnitId);
            
            CreateTable(
                "dbo.LOGProductStockMasters",
                c => new
                    {
                        ProductStockMasterId = c.Long(nullable: false, identity: true),
                        CostCentreId = c.Int(nullable: false),
                        ProductId = c.Long(nullable: false),
                        StockCode = c.String(nullable: false, maxLength: 25),
                        Stock = c.Decimal(nullable: false, precision: 18, scale: 2),
                        CostPrice = c.Decimal(nullable: false, precision: 18, scale: 2),
                        SellingPrice = c.Decimal(nullable: false, precision: 18, scale: 2),
                        ForignCustomerPrice = c.Decimal(nullable: false, precision: 18, scale: 2),
                        ReOrderLevel = c.Decimal(nullable: false, precision: 18, scale: 2),
                        ReOrderQuantity = c.Decimal(nullable: false, precision: 18, scale: 2),
                        ReOrderPeriod = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IsDelete = c.Boolean(nullable: false),
                        ProductCode = c.String(maxLength: 20),
                        ProductName = c.String(maxLength: 100),
                        Barcode = c.String(maxLength: 30),
                        RefNo1 = c.String(maxLength: 30),
                        RefNo2 = c.String(maxLength: 30),
                        ExtendedId = c.Int(nullable: false),
                        ExtendedName = c.String(maxLength: 30),
                        PLUCode = c.String(maxLength: 5),
                        WeightPerunit = c.Decimal(nullable: false, precision: 18, scale: 2),
                        UomId = c.Int(nullable: false),
                        Unit = c.String(maxLength: 10),
                        AvgCost = c.Decimal(nullable: false, precision: 18, scale: 2),
                        FixedGP = c.Decimal(nullable: false, precision: 18, scale: 2),
                        GP = c.Decimal(nullable: false, precision: 18, scale: 2),
                        OpenBal = c.Decimal(nullable: false, precision: 18, scale: 2),
                        InitSIH = c.Decimal(nullable: false, precision: 18, scale: 2),
                        InitCost = c.Decimal(nullable: false, precision: 18, scale: 2),
                        AdjQty = c.Decimal(nullable: false, precision: 18, scale: 2),
                        IsDamage = c.Boolean(nullable: false),
                        IsActive = c.Boolean(nullable: false),
                        IsBundle = c.Boolean(nullable: false),
                        IsInitialize = c.Boolean(nullable: false),
                        DataTransfer = c.Int(nullable: false),
                        Ispacksize = c.Boolean(nullable: false),
                        Iscommission = c.Boolean(nullable: false),
                        Isdecimal = c.Boolean(nullable: false),
                        DiscountPrc = c.Decimal(nullable: false, precision: 18, scale: 2),
                        DocumentNo = c.String(maxLength: 20),
                        LastUpdatedDate = c.DateTime(),
                        MaximumDiscount = c.Decimal(nullable: false, precision: 18, scale: 2),
                        FixedDiscountPercentage = c.Decimal(nullable: false, precision: 18, scale: 2),
                        FixedDiscountAmount = c.Decimal(nullable: false, precision: 18, scale: 2),
                        MaximumDiscountPercentage = c.Decimal(nullable: false, precision: 18, scale: 2),
                        PrinterType_Id = c.Int(nullable: false),
                        GroupOfCompanyID = c.Int(nullable: false),
                        CompanyID = c.Int(nullable: false),
                        LocationId = c.Int(nullable: false),
                        CreatedUser = c.String(maxLength: 50),
                        CreatedDate = c.DateTime(nullable: false),
                        ModifiedUser = c.String(maxLength: 50),
                        ModifiedDate = c.DateTime(nullable: false),
                    })
                .PrimaryKey(t => t.ProductStockMasterId);
            
            CreateTable(
                "dbo.LOGProductTaxes",
                c => new
                    {
                        ProductTaxId = c.Long(nullable: false, identity: true),
                        ProductId = c.Long(nullable: false),
                        TaxId = c.Long(nullable: false),
                        TaxPracentage = c.Decimal(nullable: false, precision: 18, scale: 2),
                        TaxSequence = c.Int(nullable: false),
                        GroupOfCompanyID = c.Int(nullable: false),
                        CompanyID = c.Int(nullable: false),
                        LocationId = c.Int(nullable: false),
                        CreatedUser = c.String(maxLength: 50),
                        CreatedDate = c.DateTime(nullable: false),
                        ModifiedUser = c.String(maxLength: 50),
                        ModifiedDate = c.DateTime(nullable: false),
                        DataTransfer = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.ProductTaxId);
            
            CreateTable(
                "dbo.LOGReceipes",
                c => new
                    {
                        ReceipeId = c.Long(nullable: false, identity: true),
                        ProductId = c.Long(nullable: false),
                        MaterialId = c.Long(nullable: false),
                        Quantity = c.Decimal(nullable: false, precision: 18, scale: 2),
                        ProductServingUnitId = c.Long(nullable: false),
                        CostPrice = c.Decimal(nullable: false, precision: 18, scale: 2),
                        SellingPrice = c.Decimal(nullable: false, precision: 18, scale: 2),
                        ProductQty = c.Decimal(nullable: false, precision: 18, scale: 2),
                        GroupOfCompanyID = c.Int(nullable: false),
                        CompanyID = c.Int(nullable: false),
                        LocationId = c.Int(nullable: false),
                        CreatedUser = c.String(maxLength: 50),
                        CreatedDate = c.DateTime(nullable: false),
                        ModifiedUser = c.String(maxLength: 50),
                        ModifiedDate = c.DateTime(nullable: false),
                        DataTransfer = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.ReceipeId);
            
            CreateTable(
                "dbo.LOGSuppliers",
                c => new
                    {
                        SupplierID = c.Long(nullable: false, identity: true),
                        SupplierCode = c.String(nullable: false, maxLength: 15),
                        SupplierTitle = c.String(),
                        SupplierName = c.String(nullable: false, maxLength: 100),
                        Gender = c.String(nullable: false),
                        SupplierTypeID = c.Int(nullable: false),
                        ContactPersonName = c.String(maxLength: 100),
                        BillingAddress1 = c.String(nullable: false, maxLength: 250),
                        BillingAddress2 = c.String(maxLength: 100),
                        BillingAddress3 = c.String(maxLength: 100),
                        BillingTelephone = c.String(nullable: false, maxLength: 50),
                        BillingMobile = c.String(maxLength: 50),
                        BillingFax = c.String(maxLength: 50),
                        Email = c.String(maxLength: 100),
                        RepresentativeName = c.String(maxLength: 100),
                        RepresentativeNICNo = c.String(maxLength: 50),
                        PayeeName = c.String(maxLength: 100),
                        DeliveryAddress1 = c.String(maxLength: 50),
                        DeliveryAddress2 = c.String(maxLength: 50),
                        DeliveryAddress3 = c.String(maxLength: 50),
                        DeliveryTelephone = c.String(maxLength: 50),
                        DeliveryMobile = c.String(maxLength: 50),
                        DeliveryFax = c.String(maxLength: 50),
                        SupplierPicture = c.Binary(),
                        SupplierPictureName = c.String(),
                        SupplierPictureType = c.String(),
                        ReferenceNo = c.String(maxLength: 20),
                        ReferenceSerial = c.String(maxLength: 20),
                        PostalCode = c.String(maxLength: 20),
                        TaxID1 = c.Int(nullable: false),
                        TaxNo1 = c.String(maxLength: 25),
                        TaxID2 = c.Int(nullable: false),
                        TaxNo2 = c.String(maxLength: 25),
                        TaxID3 = c.Int(nullable: false),
                        TaxNo3 = c.String(maxLength: 25),
                        TaxID4 = c.Int(nullable: false),
                        TaxNo4 = c.String(maxLength: 25),
                        TaxID5 = c.Int(nullable: false),
                        TaxNo5 = c.String(maxLength: 25),
                        TaxRegistrationNo = c.String(maxLength: 50),
                        TaxRegistrationName = c.String(maxLength: 100),
                        PaymentMethod = c.Int(nullable: false),
                        CreditLimit = c.Decimal(nullable: false, precision: 18, scale: 2),
                        ChequeLimit = c.Decimal(nullable: false, precision: 18, scale: 2),
                        ChequePeriod = c.Int(nullable: false),
                        PaymentTermID = c.Int(nullable: false),
                        CreditPeriod = c.Int(nullable: false),
                        ProductBusinessType = c.String(maxLength: 200),
                        SuppliedProducts = c.String(maxLength: 200),
                        OrderCircle = c.Int(nullable: false),
                        SupplierGroupID = c.Int(nullable: false),
                        LedgerID = c.Long(nullable: false),
                        OtherLedgerID = c.Long(nullable: false),
                        TaxIdNo = c.String(maxLength: 50),
                        DepositeAmount = c.Decimal(nullable: false, precision: 18, scale: 2),
                        EmailBoday = c.String(maxLength: 100),
                        EmailSubject = c.String(maxLength: 100),
                        Remark = c.String(maxLength: 100),
                        IsUpload = c.Boolean(nullable: false),
                        IsSuspended = c.Boolean(nullable: false),
                        IsPOMail = c.Boolean(nullable: false),
                        IsBlocked = c.Boolean(nullable: false),
                        IsDelete = c.Boolean(nullable: false),
                        GroupOfCompanyID = c.Int(nullable: false),
                        CompanyID = c.Int(nullable: false),
                        LocationId = c.Int(nullable: false),
                        CreatedUser = c.String(maxLength: 50),
                        CreatedDate = c.DateTime(nullable: false),
                        ModifiedUser = c.String(maxLength: 50),
                        ModifiedDate = c.DateTime(nullable: false),
                        DataTransfer = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.SupplierID);
            
            CreateTable(
                "dbo.LOGSupplierProducts",
                c => new
                    {
                        SupplierProductId = c.Long(nullable: false, identity: true),
                        SupplierId = c.Int(nullable: false),
                        ProductId = c.Int(nullable: false),
                        IsPreferredSupplier = c.Boolean(nullable: false),
                        LastCostPrice = c.Decimal(nullable: false, precision: 18, scale: 2),
                        GroupOfCompanyID = c.Int(nullable: false),
                        CompanyID = c.Int(nullable: false),
                        LocationId = c.Int(nullable: false),
                        CreatedUser = c.String(maxLength: 50),
                        CreatedDate = c.DateTime(nullable: false),
                        ModifiedUser = c.String(maxLength: 50),
                        ModifiedDate = c.DateTime(nullable: false),
                        DataTransfer = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.SupplierProductId);
            
            CreateTable(
                "dbo.LOGUnitConversions",
                c => new
                    {
                        UnitConversionId = c.Long(nullable: false, identity: true),
                        UnitOfMeasureId = c.Long(nullable: false),
                        SubUnit = c.String(nullable: false),
                        BaseUnitValue = c.Decimal(nullable: false, precision: 18, scale: 2),
                        SubUnitValue = c.Decimal(nullable: false, precision: 18, scale: 2),
                        SubUnitSymbol = c.String(nullable: false),
                        GroupOfCompanyID = c.Int(nullable: false),
                        CompanyID = c.Int(nullable: false),
                        LocationId = c.Int(nullable: false),
                        CreatedUser = c.String(maxLength: 50),
                        CreatedDate = c.DateTime(nullable: false),
                        ModifiedUser = c.String(maxLength: 50),
                        ModifiedDate = c.DateTime(nullable: false),
                        DataTransfer = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.UnitConversionId);
            
        }
        
        public override void Down()
        {
            DropTable("dbo.LOGUnitConversions");
            DropTable("dbo.LOGSupplierProducts");
            DropTable("dbo.LOGSuppliers");
            DropTable("dbo.LOGReceipes");
            DropTable("dbo.LOGProductTaxes");
            DropTable("dbo.LOGProductStockMasters");
            DropTable("dbo.LOGProductServingUnits");
            DropTable("dbo.LOGProducts");
            DropTable("dbo.LOGInvPromotionMasters");
            DropTable("dbo.LOGCustomers");
            DropTable("dbo.LOGAddons");
        }
    }
}
