// <auto-generated />
namespace HospitalityManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _65 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_65));
        
        string IMigrationMetadata.Id
        {
            get { return "202003300506295_65"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
