// <auto-generated />
namespace HospitalityManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v262 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v262));
        
        string IMigrationMetadata.Id
        {
            get { return "202010051622588_v26-2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
