// <auto-generated />
namespace HospitalityManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v3512 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v3512));
        
        string IMigrationMetadata.Id
        {
            get { return "202104210648203_v 35-1.2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
