using RIT.HMS.Data;
using RIT.HMS.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RIT.HMS.BLL.MasterData
{
    public class BLL_UserGroup
    {
        private readonly UnitOfWork _unitofwork;
        public BLL_UserGroup()
        {
            _unitofwork = new UnitOfWork();
        }
        public BLL_UserGroup(string connection)
        {
            _unitofwork = new UnitOfWork(connection);
        }
        public List<SysUserGroup> GetUserGroups(Int32 compid)
        {
            try
            {
                List<SysUserGroup> sysusergroup = _unitofwork.UserGroupRepository.Get(ug=>ug.CompanyID==compid).OrderBy(ug => ug.UserGroupCode).ToList();
                if (sysusergroup != null)
                {
                    return sysusergroup;
                }
                else
                    return null;
            }
            catch (Exception ex)
            {

                throw;
            }
        }
        public List<SysUserFunction> GetUserFunctions(Int32 compid)
        {
            try
            {
                List<SysUserFunction> functions = _unitofwork.UserFunctionRepository.Get(ug => ug.IsDelete == false).OrderBy(ug => ug.FunctionName).ToList();
                if (functions != null)
                {
                    return functions;
                }
                else
                    return null;
            }
            catch (Exception ex)
            {

                throw;
            }
        }

        public List<SysUserFunction> GetUserFunctionsToSelect(Int32 compid)
        {
            try
            {

                var dbfunctions = (from f in _unitofwork.UserFunctionRepository.Get(ug => ug.IsDelete == false) join
                                        a in _unitofwork.AutoGeneratedInfoRepository.Get(a => a.CompanyId == compid) on f.FormId equals a.FormId
                                        into k from abc in k.DefaultIfEmpty()
                                        orderby f.FormId, f.FunctionName
                                        select new SysUserFunction
                                        {
                                           SysUserFunctionID = f.SysUserFunctionID,
                                           FunctionName = f.FunctionName,
                                           FunctionDescription = f.FunctionDescription,
                                           FunctionCategory = abc == null ? "Master & POS" : abc.FormName,
                                           FormId=f.FormId

                                        }
                                    ).ToList();

                return dbfunctions;
            }
            catch (Exception ex)
            {

                throw;
            }
        }


        public IEnumerable<CashierFunction> GetCashierFunctions()
        {
            try
            {
                IEnumerable<CashierFunction> functions = _unitofwork.CashierFunctionRepository.Get().OrderBy(ug => ug.FunctionName);
                if (functions != null)
                {
                    return functions;
                }
                else
                    return null;
            }
            catch (Exception ex)
            {

                throw;
            }
        }

        public CashierFunction GetCashierFunctionById(long id)
        {
            try
            {
                CashierFunction functions = _unitofwork.CashierFunctionRepository.GetById(id);
                if (functions != null)
                {
                    return functions;
                }
                else
                    return null;
            }
            catch (Exception ex)
            {

                throw;
            }
        }

        public SysUserFunction GetUserFunction(long id)
        {
            try
            {
               
                SysUserFunction function = _unitofwork.UserFunctionRepository.Get(f => f.SysUserFunctionID == id).FirstOrDefault();
                if (function != null)
                {
                    return function;
                }
                else
                    return null;
            }
            catch (Exception ex)
            {

                throw;
            }
        }

        public SysUserFunction GetUserFunctionReportInfo(long id,int companyid)
        {
            try
            {

                var function = _unitofwork.ReportInfoRepository.Get(f => f.ReportInfoId == id && f.CompanyID== companyid).FirstOrDefault();
                if (function != null)
                {
                    SysUserFunction reportinfor = new SysUserFunction();
                    reportinfor.SysUserFunctionID = Convert.ToInt32(function.ReportInfoId);
                    reportinfor.FunctionName = "SSRS"+function.ReportName.Replace(" ","");
                    reportinfor.FunctionDescription = function.ReportName;
                    reportinfor.FormId = 999;
                    return reportinfor;
                }
                else
                    return null;
            }
            catch (Exception ex)
            {

                throw;
            }
        }
        public IEnumerable<SysUserGroup> GetActiveUserGroups(Int32 compid)
        {
            try
            {
                IEnumerable<SysUserGroup> sysusergroup = _unitofwork.UserGroupRepository.Get(ug => ug.IsDelete == false && ug.CompanyID==compid).OrderBy(ug => ug.UserGroupCode);
                if (sysusergroup != null)
                {
                    return sysusergroup;

                }
                else
                    return null;
            }
            catch (Exception ex)
            {

                throw;
            }
        }

        public IEnumerable<POSUserGroup> GetActivePOSUserGroups()
        {
            try
            {
                IEnumerable<POSUserGroup> posusergroup = _unitofwork.POSUserGroupRepository.Get(ug => ug.IsDelete == false && ug.IsActive == true).OrderBy(ug => ug.POSUserGroupName);
                if (posusergroup != null)
                {
                    return posusergroup;

                }
                else
                    return null;
            }
            catch (Exception ex)
            {

                throw;
            }
        }

        public SysUserGroup GetUserGroupById(long id)
        {
            try
            {
                SysUserGroup sysusergroup = _unitofwork.UserGroupRepository.Get(ug => ug.SysUserGroupID == id).FirstOrDefault();
                if (sysusergroup != null)
                {
                    return sysusergroup;
                }
                else
                    return null;
            }
            catch (Exception ex)
            {

                throw;
            }
        }

        public SysUserGroup GetUserGroupByCode(string code, Int32 compid)
        {
            try
            {
                SysUserGroup usergroup = _unitofwork.UserGroupRepository.Get(g => g.UserGroupCode == code && g.CompanyID==compid).FirstOrDefault();
                if (usergroup != null)
                {
                    return usergroup;
                }
                else
                    return null;
            }
            catch (Exception)
            {

                throw;
            }
        }

        public int SaveUserGroup(SysUserGroup ug)
        {
            try
            {
                _unitofwork.UserGroupRepository.Insert(ug);
                return _unitofwork.Save();

            }
            catch (Exception ex)
            {
                return 0;
            }
        }

        public int UpdateUserGroup(SysUserGroup ug)
        {
            try
            {
                _unitofwork.UserGroupRepository.Update(ug);
                return _unitofwork.Save();

            }
            catch (Exception ex)
            {
                return 0;
            }
        }




    }
}
