using RIT.HMS.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RIT.HMS.BLL.MasterData
{
    public class BLL_CheckDependency
    {
        private readonly UnitOfWork _unitofwork;
        public BLL_CheckDependency()
        {
            _unitofwork = new UnitOfWork();
        }
        public BLL_CheckDependency(string connectionname)
        {
            _unitofwork = new UnitOfWork(connectionname);
        }
        public bool CheckDependency(string formname)
        {
            try
            {
                bool IsDepend = _unitofwork.AutoGeneratedInfoRepository.Get(g => g.FormName == formname).FirstOrDefault().IsDepend;
                if (IsDepend != null)
                {
                    return IsDepend;
                }
                else
                    return false;
            }
            catch (Exception ex)
            {

                throw;
            }
        }


    }
}
