using RIT.HMS.Data;
using RIT.HMS.Domain;
using RIT.HMS.Domain.Common;
using RIT.HMS.Domain.Loyalty;
using RIT.HMS.Domain.ViewModels.Reports;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RIT.HMS.BLL.Loyalty
{
     public  class BLL_CardMaster
    {
        UnitOfWork _unitofwork;
       public BLL_CardMaster()
       {
            _unitofwork = new UnitOfWork();
       }
        public BLL_CardMaster(string connection)
        {
            _unitofwork = new UnitOfWork(connection);
        }
        public List<ReferenceType> GetReferanceTypes(string lookuptype,int companyid)
        {
            var referances = _unitofwork.ReferenceTypeRepository.Get(r=>r.LookupType == lookuptype && r.CompanyID== companyid).ToList();
            return referances == null ? null : referances;
        }

        public List<CardMaster> GetAllActiveCards(int companyid)
        {
            var cards = _unitofwork.CardMasterRepository.Get(c=>c.IsDelete==false && c.CompanyID==companyid).ToList();
            return cards == null ? null : cards;
        }

        public CardMaster GetCardById(int id)
        {
            var card = _unitofwork.CardMasterRepository.GetById(id) ;
            return card == null ? null : card;
        }

        public string GetNewCode(string formName)
        {
            AutoGenerateInfo autoGenerateInfo;
            autoGenerateInfo = _unitofwork.AutoGeneratedInfoRepository.Get(a=>a.FormName==formName).FirstOrDefault();
            string getNewCode = string.Empty;
            string preFix = autoGenerateInfo.Prefix;
            int codeLength = autoGenerateInfo.CodeLength;

            getNewCode = _unitofwork.CardMasterRepository.Get().Max(c => c.CardCode);
            if (getNewCode != null)
                getNewCode = getNewCode.Trim().Substring(preFix.Length, codeLength - preFix.Length);
            else
                getNewCode = "0";

            getNewCode = (int.Parse(getNewCode) + 1).ToString();
            getNewCode = preFix + new StringBuilder().Insert(0, "0", (codeLength - (preFix.Length + getNewCode.Length))) + getNewCode;
            return getNewCode;
        }

        public bool SaveCardMaster(CardMaster cardmaster)
        {
            try
            {
                _unitofwork.CreateTransaction();
                foreach (var s in cardmaster.LoyaltyCardSchems)
                {
                    s.LocationId = cardmaster.LocationId;
                    s.CreatedUser = cardmaster.CreatedUser;
                    s.CompanyID = cardmaster.CompanyID;
                }
                if (cardmaster.IsExists == false)
                {                    
                    _unitofwork.CardMasterRepository.Insert(cardmaster);
                    _unitofwork.Save();
                }
                else
                {
                    var existsheader = _unitofwork.CardMasterRepository.GetById(cardmaster.CardMasterId);
                    _unitofwork.CardMasterRepository.UpdateBySet(existsheader,cardmaster);
                    _unitofwork.LoyaltyCardSchemsRepository.DeleteRange(existsheader.LoyaltyCardSchems);
                    List<LoyaltyCardSchems> l2 = new List<LoyaltyCardSchems>();
                    foreach (var l in cardmaster.LoyaltyCardSchems)
                    {
                        LoyaltyCardSchems l1 = new LoyaltyCardSchems();
                        l1.CardMasterId = cardmaster.CardMasterId;
                        l1.BillFromValue = l.BillFromValue;
                        l1.BillToValue = l.BillToValue;
                        l1.Increment = l.Increment;
                        l1.PointValue = l.PointValue;
                        l1.PointPer = l.PointPer;
                        l1.GroupOfCompanyID = l.GroupOfCompanyID;
                        l1.CompanyID = l.CompanyID;
                        l1.LocationId = l.LocationId;
                        l1.CreatedDate = l1.CreatedDate;
                        l1.CreatedUser = l1.CreatedUser;
                        l1.ModifiedDate = l1.ModifiedDate;
                        l1.ModifiedUser = l1.ModifiedUser;
                        l1.DataTransfer = l.DataTransfer;
                        l2.Add(l1);
                    }
                    _unitofwork.LoyaltyCardSchemsRepository.BulkInsert(l2);
                    _unitofwork.Save();
                }
                _unitofwork.Commit();
                return true;
            }
            catch (Exception e)
            {
                _unitofwork.Rollback();
                return false;
            }
            
        }

        private string CreateSQL(int cardmastertype,string fm,DateTime fd,string sm,DateTime sd,int locid,int compid)
        {
            string q = "INSERT INTO [SMS].[dbo].[TBLM_MessegeHead]([MessegeID],[MsgParam],[Recever],[Status],[CreateDate],[LocationId]) VALUES";

            var recivers = (from lc in _unitofwork.LoyaltyCustomerReporsitory.Get()
                           join c in _unitofwork.CustomerRepository.Get() on lc.CustomerId equals c.CustomerID
                           where lc.CardMasterId == cardmastertype && c.LocationId == locid && c.CompanyID == compid
                           select new
                           {
                               MobileNo = c.Mobile                     
                           }
                        ).ToList();
            if (!string.IsNullOrEmpty(fm))
            {
                foreach (var r in recivers)
                {
                    q += "(1,'#" + fm + "'," + r.MobileNo + ",'0','" + DateTime.Now.ToString("yyyy-MM-dd") + "'," + locid + "),";
                }
            }
            if (!string.IsNullOrEmpty(sm))
            {
                foreach (var r in recivers)
                {
                    q += "(1,'#" + sm + "'," + r.MobileNo + ",'0','" + DateTime.Now.ToString("yyyy-MM-dd") + "'," + locid + "),";
                }
            }
            return q.Remove(q.Length - 1, 1);
        }
        public bool SaveExpiration(PointsExpiration pointsexp)
        {
            _unitofwork.CreateTransaction();
            try
            {
                var exists=_unitofwork.PointsExpirationReporsitory.Get(p=>p.CardType==pointsexp.CardType && p.Year==pointsexp.Year).SingleOrDefault();
                if (exists == null)
                {
                    _unitofwork.PointsExpirationReporsitory.Insert(pointsexp);
                    _unitofwork.Save();

                    PointsExpirationSchedule pointsexpschedule = new PointsExpirationSchedule();
                    pointsexpschedule.Type = 1;

                    pointsexpschedule.SQL = CreateSQL(pointsexp.CardType,pointsexp.FirstReminderMessage,
                                                      pointsexp.FirstReminderDate,pointsexp.SecontReminderMessage,
                                                      pointsexp.SecondReminderDate,pointsexp.LocationId,pointsexp.CompanyID);

                    pointsexpschedule.Date = pointsexp.PointsExpiryDate;
                    pointsexpschedule.ScheduleDate = pointsexp.FirstReminderDate;
                    pointsexpschedule.Status = 0;
                    pointsexpschedule.user = pointsexp.CreatedUser;
                    pointsexpschedule.CreatedDate = pointsexp.CreatedDate;
                    pointsexpschedule.ModifiedDate = pointsexp.ModifiedDate;
                    pointsexpschedule.LocationId = pointsexp.LocationId;
                    pointsexpschedule.CompanyID = pointsexp.CompanyID;
                    pointsexpschedule.PointsExpirationId = pointsexp.PointsExpirationId;
                    _unitofwork.PointsExpirationScheduleReporsitory.Insert(pointsexpschedule);

                    PointsExpirationSchedule pointsexpschedule1 = new PointsExpirationSchedule();
                    pointsexpschedule1.Type = 1;
                    pointsexpschedule.SQL = CreateSQL(pointsexp.CardType, pointsexp.FirstReminderMessage,
                                                      pointsexp.FirstReminderDate, pointsexp.SecontReminderMessage,
                                                      pointsexp.SecondReminderDate, pointsexp.LocationId, pointsexp.CompanyID);

                    pointsexpschedule1.Date = pointsexp.PointsExpiryDate;
                    pointsexpschedule1.ScheduleDate = pointsexp.SecondReminderDate;
                    pointsexpschedule1.Status = 0;
                    pointsexpschedule1.user = pointsexp.CreatedUser;
                    pointsexpschedule1.CreatedDate = pointsexp.CreatedDate;
                    pointsexpschedule1.ModifiedDate = pointsexp.ModifiedDate;
                    pointsexpschedule1.LocationId = pointsexp.LocationId;
                    pointsexpschedule1.CompanyID = pointsexp.CompanyID;
                    pointsexpschedule1.PointsExpirationId = pointsexp.PointsExpirationId;
                    _unitofwork.PointsExpirationScheduleReporsitory.Insert(pointsexpschedule1);
                }
                else
                {
                    exists.Year = pointsexp.Year;
                    exists.SecontReminderMessage = pointsexp.SecontReminderMessage;
                    exists.SecondReminderDate = pointsexp.SecondReminderDate;
                    exists.PointsExpiryDate = pointsexp.PointsExpiryDate;
                    exists.FirstReminderDate = pointsexp.FirstReminderDate;
                    exists.FirstReminderMessage = pointsexp.FirstReminderMessage;
                    exists.ModifiedUser = pointsexp.CreatedUser;
                    exists.ModifiedDate = pointsexp.ModifiedDate;
                    exists.LocationId = pointsexp.LocationId;
                    exists.CompanyID = pointsexp.CompanyID;
                  
                    _unitofwork.PointsExpirationReporsitory.Update(exists);
                    _unitofwork.Save();

                    _unitofwork.PointsExpirationScheduleReporsitory.DeleteRange(_unitofwork.PointsExpirationScheduleReporsitory.Get(e=>e.PointsExpirationId==exists.PointsExpirationId));

                    PointsExpirationSchedule pointsexpschedule = new PointsExpirationSchedule();
                    pointsexpschedule.Type = 1;
                    pointsexpschedule.SQL = CreateSQL(pointsexp.CardType, pointsexp.FirstReminderMessage,
                                                      pointsexp.FirstReminderDate, pointsexp.SecontReminderMessage,
                                                      pointsexp.SecondReminderDate, pointsexp.LocationId, pointsexp.CompanyID);
                    pointsexpschedule.Date = pointsexp.PointsExpiryDate;
                    pointsexpschedule.ScheduleDate = pointsexp.FirstReminderDate;
                    pointsexpschedule.Status = 0;
                    pointsexpschedule.user = pointsexp.CreatedUser;
                    pointsexpschedule.CreatedDate = pointsexp.CreatedDate;
                    pointsexpschedule.ModifiedDate = pointsexp.ModifiedDate;
                    pointsexpschedule.LocationId = pointsexp.LocationId;
                    pointsexpschedule.CompanyID = pointsexp.CompanyID;
                    pointsexpschedule.PointsExpirationId = exists.PointsExpirationId;
                    _unitofwork.PointsExpirationScheduleReporsitory.Insert(pointsexpschedule);

                    PointsExpirationSchedule pointsexpschedule1 = new PointsExpirationSchedule();
                    pointsexpschedule1.Type = 1;
                    pointsexpschedule1.SQL = CreateSQL(pointsexp.CardType, pointsexp.FirstReminderMessage,
                                                      pointsexp.FirstReminderDate, pointsexp.SecontReminderMessage,
                                                      pointsexp.SecondReminderDate, pointsexp.LocationId, pointsexp.CompanyID);
                    pointsexpschedule1.Date = pointsexp.PointsExpiryDate;
                    pointsexpschedule1.ScheduleDate = pointsexp.SecondReminderDate;
                    pointsexpschedule1.Status = 0;
                    pointsexpschedule1.user = pointsexp.CreatedUser;
                    pointsexpschedule1.CreatedDate = pointsexp.CreatedDate;
                    pointsexpschedule1.ModifiedDate = pointsexp.ModifiedDate;
                    pointsexpschedule1.LocationId = pointsexp.LocationId;
                    pointsexpschedule1.CompanyID = pointsexp.CompanyID;
                    pointsexpschedule1.PointsExpirationId = exists.PointsExpirationId;
                    _unitofwork.PointsExpirationScheduleReporsitory.Insert(pointsexpschedule1);



                }
                if (_unitofwork.Save() > 0)
                {
                    _unitofwork.Commit();
                    return true;
                }
                else
                {
                    _unitofwork.Rollback();
                    return false;
                }


            }
            catch (Exception e)
            {
                _unitofwork.Rollback();
                return false;
            }
           
        }

        public CustomerStatementViewModel CustomerStatement(int customerid)
        {

            CustomerStatementViewModel statement = new CustomerStatementViewModel();
            statement.CustomerId = customerid;
            List<CustomerStatementViewModel.PointsDetail> details = new List<CustomerStatementViewModel.PointsDetail>();
            List<InvLoyaltyTransaction> loyaltytransactions = new List<InvLoyaltyTransaction>();
            if (customerid != 0)
            {
                loyaltytransactions = _unitofwork.InvLoyaltyTransactionReporsitory.Get(t => t.CustomerID == customerid).ToList();
            }
            else
            {
                loyaltytransactions = _unitofwork.InvLoyaltyTransactionReporsitory.Get().ToList();
            }

            foreach (var s in loyaltytransactions)
            {
                CustomerStatementViewModel.PointsDetail detail = new CustomerStatementViewModel.PointsDetail();
                detail.CustomerName = _unitofwork.CustomerRepository.GetById(s.CustomerID).CustomerName;
                detail.Recipt = s.Receipt;
                detail.Amount = s.Amount;
                detail.Points = s.Points;
                detail.CardNumber = s.CardNo;
                details.Add(detail);
            }
            statement.Detail = details;
            return statement;
        }

        public CustomerStatementViewModel CustomerStatementSummary(int customerid)
        {

            CustomerStatementViewModel statement = new CustomerStatementViewModel();
            statement.CustomerId = customerid;
            List<CustomerStatementViewModel.PointsDetail> details = new List<CustomerStatementViewModel.PointsDetail>();
            List<InvLoyaltyTransaction> loyaltytransactions = new List<InvLoyaltyTransaction>();
            if (customerid != 0)
            {
                loyaltytransactions = _unitofwork.InvLoyaltyTransactionReporsitory.Get(t => t.CustomerID == customerid).ToList();
            }
            else
            {
                loyaltytransactions = _unitofwork.InvLoyaltyTransactionReporsitory.Get().ToList();
            }

            foreach (var s in loyaltytransactions)
            {
                CustomerStatementViewModel.PointsDetail detail = new CustomerStatementViewModel.PointsDetail();
                detail.CustomerName = _unitofwork.CustomerRepository.GetById(s.CustomerID).CustomerName;
                detail.Recipt = s.Receipt;
                detail.Amount = s.Amount;
                detail.Points = s.Points;
                detail.CardNumber = s.CardNo;
                details.Add(detail);
            }
            statement.Detail = details;
            return statement;
        }

    }
}
