//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIT.HMS.HMSOrderTaker.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addon
    {
        public int AddonsId { get; set; }
        public long ProductId { get; set; }
        public long ProductAddonId { get; set; }
        public long DepartmentId { get; set; }
        public bool IsActive { get; set; }
        public int GroupOfCompanyID { get; set; }
        public int CompanyID { get; set; }
        public int LocationId { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int DataTransfer { get; set; }
        public decimal AddonSellingPrice { get; set; }
        public decimal AddonQuantity { get; set; }
        public bool IsShowOnBill { get; set; }
    }
}
