//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIT.HMS.HMSOrderTaker.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoGenerateInfo
    {
        public long AutoGenerateInfoID { get; set; }
        public int ModuleType { get; set; }
        public int DocumentID { get; set; }
        public int FormId { get; set; }
        public string FormName { get; set; }
        public string FormText { get; set; }
        public string Prefix { get; set; }
        public string Prefix2 { get; set; }
        public int CodeLength { get; set; }
        public int Suffix { get; set; }
        public bool AutoGenerete { get; set; }
        public bool AutoClear { get; set; }
        public bool IsDepend { get; set; }
        public bool IsDependCode { get; set; }
        public bool IsSupplierProduct { get; set; }
        public bool IsOverWriteQty { get; set; }
        public bool IsLocationCode { get; set; }
        public string ReportPrefix { get; set; }
        public int ReportType { get; set; }
        public bool PoIsMandatory { get; set; }
        public bool IsDispatchRecall { get; set; }
        public bool IsBackDated { get; set; }
        public bool IsCard { get; set; }
        public int CardId { get; set; }
        public bool IsEntry { get; set; }
        public bool IsSlabReport { get; set; }
        public bool IsConsignment { get; set; }
        public bool IsRoundOff { get; set; }
        public bool IsAutoComplete { get; set; }
        public bool IsUpdateProductImage { get; set; }
        public bool IsAllowedInHO { get; set; }
        public bool IsAllowedInOutlet { get; set; }
        public bool IsActive { get; set; }
        public string Layout { get; set; }
        public string LayoutNew { get; set; }
        public int ReferenceDocumentID { get; set; }
        public string Separator { get; set; }
        public int CompanyId { get; set; }
    }
}
