//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIT.HMS.HMSOrderTaker.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashierPermission
    {
        public long CashierPermissionId { get; set; }
        public long LocationId { get; set; }
        public long CashierId { get; set; }
        public long EmployeeId { get; set; }
        public string Password { get; set; }
        public string JournalName { get; set; }
        public string EnCode { get; set; }
        public string FunctionName { get; set; }
        public string FunctionDescription { get; set; }
        public long Order { get; set; }
        public long Value { get; set; }
        public decimal MaxValue { get; set; }
        public string Type { get; set; }
        public string TypeID { get; set; }
        public bool IsActive { get; set; }
        public bool IsAccess { get; set; }
        public string Remarks { get; set; }
        public bool IsDelete { get; set; }
        public bool IsValue { get; set; }
        public int GroupOfCompanyId { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int DataTransfer { get; set; }
    }
}
