//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIT.HMS.HMSOrderTaker.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashierGroup
    {
        public int CashierGroupId { get; set; }
        public int EmployeeGroupId { get; set; }
        public string FunctionName { get; set; }
        public string FunctionDescription { get; set; }
        public int Order { get; set; }
        public decimal Value { get; set; }
        public string Type { get; set; }
        public int TypeId { get; set; }
        public bool IsAccess { get; set; }
        public bool IsValue { get; set; }
        public int GroupOfCompanyId { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int DataTransfer { get; set; }
    }
}
