//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIT.HMS.HMSOrderTaker.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CateringMood
    {
        public long CateringMoodID { get; set; }
        public string CateringMoodName { get; set; }
        public string OrderSequence { get; set; }
        public bool IsActive { get; set; }
        public bool IsServiceCharge { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int CompanyId { get; set; }
    }
}
