//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIT.HMS.HMSOrderTaker.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CateringModeTax
    {
        public long CateringModeTaxId { get; set; }
        public long CateringModeId { get; set; }
        public long TaxId { get; set; }
        public decimal TaxPracentage { get; set; }
        public int TaxSequence { get; set; }
        public int GroupOfCompanyID { get; set; }
        public int CompanyID { get; set; }
        public int LocationId { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int DataTransfer { get; set; }
    }
}
