//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIT.HMS.HMSOrderTaker.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration
    {
        public int ConfigurationId { get; set; }
        public string ConfigurationKey { get; set; }
        public string ConfigurationDescription { get; set; }
        public int EffectLocationId { get; set; }
        public bool ConfigurationOn { get; set; }
        public bool ConfigurationActive { get; set; }
        public bool ConfigurationDelete { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public int CreateUserId { get; set; }
        public int CompanyId { get; set; }
    }
}
