//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIT.HMS.HMSOrderTaker.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerID { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerTitle { get; set; }
        public string CustomerName { get; set; }
        public string CustomerType { get; set; }
        public int CustomerCategoryId { get; set; }
        public string BillingAddress1 { get; set; }
        public string BillingAddress2 { get; set; }
        public string BillingAddress3 { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string NIC { get; set; }
        public string Passport { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string VehicleNo { get; set; }
        public string Profession { get; set; }
        public Nullable<System.DateTime> WeddingAnniversary { get; set; }
        public bool IsActiveForLoyalty { get; set; }
        public byte[] CustomerPicture { get; set; }
        public string CustomerPictureName { get; set; }
        public string CustomerPictureType { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public decimal CreditLimit { get; set; }
        public decimal Outstanding { get; set; }
        public string EPFNo { get; set; }
        public string MembershipCardNo { get; set; }
        public string Other { get; set; }
        public string Remarks { get; set; }
        public string CustomerStatus { get; set; }
        public int GroupOfCompanyID { get; set; }
        public int CompanyID { get; set; }
        public int LocationId { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int DataTransfer { get; set; }
        public int Gender { get; set; }
        public string ReferenceNo1 { get; set; }
        public string ReferenceNo2 { get; set; }
        public int Age { get; set; }
        public Nullable<int> Religion { get; set; }
        public Nullable<int> Race { get; set; }
        public string LandMark { get; set; }
        public string District { get; set; }
        public string Organization { get; set; }
        public string WorkAddres1 { get; set; }
        public string WorkAddres2 { get; set; }
        public string WorkAddres3 { get; set; }
        public string WorkEmail { get; set; }
        public string WorkTelephone { get; set; }
        public string WorkMobile { get; set; }
        public string WorkFax { get; set; }
        public string SpouseName { get; set; }
        public int CivilStatus { get; set; }
        public Nullable<System.DateTime> SpouseDateOfBirth { get; set; }
        public int DeliverTo { get; set; }
        public string DeliverToAddress { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> CustomerSince { get; set; }
        public int SpecialDayType { get; set; }
        public bool SendUpdatesViaEmail { get; set; }
        public bool SendUpdatesViaSms { get; set; }
        public bool IsRegByPOS { get; set; }
    }
}
