//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIT.HMS.HMSOrderTaker.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryPerson
    {
        public long DeliveryPersonId { get; set; }
        public string EmployeeId { get; set; }
        public string Title { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public System.DateTime DOB { get; set; }
        public string Designation { get; set; }
        public byte[] Picture { get; set; }
        public string PictureName { get; set; }
        public string PictureType { get; set; }
        public string NIC { get; set; }
        public string DrivingLicence { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string InCaseOfEmergency { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public int GroupOfCompanyID { get; set; }
        public int CompanyID { get; set; }
        public int LocationId { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int DataTransfer { get; set; }
    }
}
