//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIT.HMS.HMSOrderTaker.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentNumbers_17112020
    {
        public long DocumentNumberId { get; set; }
        public int DocumentId { get; set; }
        public string DocumentName { get; set; }
        public long DocumentNo { get; set; }
        public long TempDocumentNo { get; set; }
        public string TemplateDocumentNo { get; set; }
        public int DocumentYear { get; set; }
        public string PrefixCode { get; set; }
        public int GroupOfCompanyID { get; set; }
        public int CompanyID { get; set; }
        public int LocationId { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int DataTransfer { get; set; }
    }
}
