//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIT.HMS.HMSOrderTaker.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartLinkEntities : DbContext
    {
        public SmartLinkEntities()
            : base("name=SmartLinkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddonCategoryMaster> AddonCategoryMasters { get; set; }
        public virtual DbSet<Addon> Addons { get; set; }
        public virtual DbSet<CashierFunction> CashierFunctions { get; set; }
        public virtual DbSet<CashierPermission> CashierPermissions { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<CustomerCategory> CustomerCategories { get; set; }
        public virtual DbSet<CustomerDiscount> CustomerDiscounts { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DeliveryPerson> DeliveryPersons { get; set; }
        public virtual DbSet<EmployeeGroup> EmployeeGroups { get; set; }
        public virtual DbSet<KOTBOTDescription> KOTBOTDescriptions { get; set; }
        public virtual DbSet<ProductInstruction> ProductInstructions { get; set; }
        public virtual DbSet<ProductServingUnit> ProductServingUnits { get; set; }
        public virtual DbSet<ProductTax> ProductTaxes { get; set; }
        public virtual DbSet<RstCategory> RstCategories { get; set; }
        public virtual DbSet<RstDepartment> RstDepartments { get; set; }
        public virtual DbSet<RstSubCategory> RstSubCategories { get; set; }
        public virtual DbSet<StewardsMaster> StewardsMasters { get; set; }
        public virtual DbSet<SysLocation> SysLocations { get; set; }
        public virtual DbSet<TableMaster> TableMasters { get; set; }
        public virtual DbSet<UnitOfMeasure> UnitOfMeasures { get; set; }
        public virtual DbSet<InterDepartment> InterDepartments { get; set; }
        public virtual DbSet<KitchenMaster> KitchenMasters { get; set; }
        public virtual DbSet<LocationTax> LocationTaxes { get; set; }
        public virtual DbSet<Receipe> Receipes { get; set; }
        public virtual DbSet<RstKotCategory> RstKotCategories { get; set; }
        public virtual DbSet<ServingUnit> ServingUnits { get; set; }
        public virtual DbSet<AutoGenerateInfo> AutoGenerateInfoes { get; set; }
        public virtual DbSet<CashierGroup> CashierGroups { get; set; }
        public virtual DbSet<CateringModeTax> CateringModeTaxes { get; set; }
        public virtual DbSet<ChairMaster> ChairMasters { get; set; }
        public virtual DbSet<Configuration> Configurations { get; set; }
        public virtual DbSet<CustomoerPreviousVisit> CustomoerPreviousVisits { get; set; }
        public virtual DbSet<DocumentNumber> DocumentNumbers { get; set; }
        public virtual DbSet<LoyaltyCustomer> LoyaltyCustomers { get; set; }
        public virtual DbSet<POSUserGroup> POSUserGroups { get; set; }
        public virtual DbSet<PrinterType> PrinterTypes { get; set; }
        public virtual DbSet<RstMealType> RstMealTypes { get; set; }
        public virtual DbSet<SysCompany> SysCompanies { get; set; }
        public virtual DbSet<SysGroupOfCompany> SysGroupOfCompanies { get; set; }
        public virtual DbSet<DocumentNumbers_17112020> DocumentNumbers_17112020 { get; set; }
        public virtual DbSet<ProductServingUnits_18112020> ProductServingUnits_18112020 { get; set; }
        public virtual DbSet<Receipes_30112020> Receipes_30112020 { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<STOS_TabOrderDetail> STOS_TabOrderDetail { get; set; }
        public virtual DbSet<STOS_TabOrderHeader> STOS_TabOrderHeader { get; set; }
        public virtual DbSet<STOS_TabOrderConfirmationDetail> STOS_TabOrderConfirmationDetail { get; set; }
        public virtual DbSet<STOS_TabOrderConfirmationHeader> STOS_TabOrderConfirmationHeader { get; set; }
        public virtual DbSet<SuspendDet> SuspendDets { get; set; }
        public virtual DbSet<SuspendHed> SuspendHeds { get; set; }
        public virtual DbSet<TransactionDet> TransactionDets { get; set; }
        public virtual DbSet<CateringMood> CateringMoods { get; set; }
        public virtual DbSet<ProductStockMaster> ProductStockMasters { get; set; }
    }
}
