//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIT.HMS.HMSOrderTaker.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoyaltyCustomer
    {
        public int LoyaltyCustomerId { get; set; }
        public string CardNo { get; set; }
        public long CustomerId { get; set; }
        public string NameOnCard { get; set; }
        public long CardMasterId { get; set; }
        public bool CardIssued { get; set; }
        public System.DateTime IssuedOn { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public System.DateTime RenewedOn { get; set; }
        public long LedgerId { get; set; }
        public long LedgerId2 { get; set; }
        public decimal CreditLimit { get; set; }
        public int CreditPeriod { get; set; }
        public decimal CPoints { get; set; }
        public decimal EPoints { get; set; }
        public decimal RPoints { get; set; }
        public bool IsReDimm { get; set; }
        public System.DateTime AcitiveDate { get; set; }
        public int LocationID { get; set; }
        public int CashierID { get; set; }
        public int LoyaltyType { get; set; }
        public string Remark { get; set; }
        public string SystemGeneratedCode { get; set; }
        public decimal ExpiryPoints { get; set; }
        public bool IsSold { get; set; }
        public int GroupOfCompanyID { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int DataTransfer { get; set; }
        public decimal ExpiryPoints1 { get; set; }
        public decimal Discount { get; set; }
        public string SalesPersonCode { get; set; }
        public int LastUpdatedLocId { get; set; }
        public int Status { get; set; }
        public int IsCardIssued { get; set; }
        public int CompanyId { get; set; }
    }
}
