//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIT.HMS.HMSOrderTaker.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStockMaster
    {
        public long ProductStockMasterId { get; set; }
        public int CostCentreId { get; set; }
        public long ProductId { get; set; }
        public string StockCode { get; set; }
        public decimal Stock { get; set; }
        public decimal CostPrice { get; set; }
        public decimal SellingPrice { get; set; }
        public decimal ReOrderLevel { get; set; }
        public decimal ReOrderQuantity { get; set; }
        public decimal ReOrderPeriod { get; set; }
        public bool IsDelete { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string Barcode { get; set; }
        public string RefNo1 { get; set; }
        public string RefNo2 { get; set; }
        public int ExtendedId { get; set; }
        public string ExtendedName { get; set; }
        public string PLUCode { get; set; }
        public decimal WeightPerunit { get; set; }
        public int UomId { get; set; }
        public string Unit { get; set; }
        public decimal AvgCost { get; set; }
        public decimal FixedGP { get; set; }
        public decimal GP { get; set; }
        public decimal OpenBal { get; set; }
        public decimal InitSIH { get; set; }
        public decimal InitCost { get; set; }
        public decimal AdjQty { get; set; }
        public bool IsDamage { get; set; }
        public bool IsActive { get; set; }
        public bool IsBundle { get; set; }
        public bool IsInitialize { get; set; }
        public int DataTransfer { get; set; }
        public bool Ispacksize { get; set; }
        public bool Iscommission { get; set; }
        public bool Isdecimal { get; set; }
        public int GroupOfCompanyID { get; set; }
        public int CompanyID { get; set; }
        public int LocationId { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public decimal DiscountPrc { get; set; }
        public string DocumentNo { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public decimal ForignCustomerPrice { get; set; }
        public decimal MaximumDiscount { get; set; }
        public decimal FixedDiscountPercentage { get; set; }
        public decimal FixedDiscountAmount { get; set; }
        public decimal MaximumDiscountPercentage { get; set; }
        public int PrinterType_Id { get; set; }
    }
}
