//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIT.HMS.HMSOrderTaker.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class RstKotCategory
    {
        public int RstKotCategoryID { get; set; }
        public string RstKotCategoryCode { get; set; }
        public string RstKotCategoryName { get; set; }
        public string IPAddress { get; set; }
        public string PrinterName { get; set; }
        public string COMName { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public int GroupOfCompanyID { get; set; }
        public int CompanyID { get; set; }
        public int LocationId { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int DataTransfer { get; set; }
    }
}
