//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIT.HMS.HMSOrderTaker.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOS_TabOrderDetail
    {
        public int LocationId { get; set; }
        public int OrderSeqNumber { get; set; }
        public int ItemSeqId { get; set; }
        public int ItemId { get; set; }
        public string ItemCode { get; set; }
        public string ItemNameOnBill { get; set; }
        public string ItemName { get; set; }
        public int TableId { get; set; }
        public string TableCode { get; set; }
        public Nullable<decimal> ItemCostPrice { get; set; }
        public Nullable<decimal> ItemSellingPrice { get; set; }
        public Nullable<int> IsItemOnPromotion { get; set; }
        public Nullable<int> ItemQty { get; set; }
        public Nullable<int> ItemServingTypeid { get; set; }
        public string ItemServingTypeName { get; set; }
        public Nullable<int> IsWithAddOn { get; set; }
        public string OrderedItemRemark { get; set; }
        public Nullable<int> ItemKOTBOT { get; set; }
        public Nullable<int> ItemKOTBOTStatus { get; set; }
        public Nullable<System.DateTime> ItemKOTBOTStartDateTime { get; set; }
        public Nullable<System.DateTime> ItemKOTBOTEndDateTime { get; set; }
        public Nullable<int> OrderedItemStatus { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string CreatedMachine { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string ModifiedMachine { get; set; }
        public Nullable<int> ProductServingUnitId { get; set; }
        public string ServingUnit { get; set; }
    }
}
