//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIT.HMS.HMSOrderTaker.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuspendDet
    {
        public int Idx { get; set; }
        public int ProductID { get; set; }
        public string ProductCode { get; set; }
        public string RefCode { get; set; }
        public long BarCodeFull { get; set; }
        public string Descrip { get; set; }
        public string BatchNo { get; set; }
        public string SerialNo { get; set; }
        public Nullable<System.DateTime> ExpiaryDate { get; set; }
        public decimal Cost { get; set; }
        public decimal AvgCost { get; set; }
        public decimal Qty { get; set; }
        public decimal Amount { get; set; }
        public int UnitOfMeasureID { get; set; }
        public string UnitOfMeasureName { get; set; }
        public decimal ConvertFactor { get; set; }
        public int IDI1 { get; set; }
        public decimal IDis1 { get; set; }
        public decimal IDiscount1 { get; set; }
        public int IDI1CashierID { get; set; }
        public int IDI2 { get; set; }
        public decimal IDis2 { get; set; }
        public decimal IDiscount2 { get; set; }
        public int IDI2CashierID { get; set; }
        public int IDI3 { get; set; }
        public decimal IDis3 { get; set; }
        public decimal IDiscount3 { get; set; }
        public int IDI3CashierID { get; set; }
        public int IDI4 { get; set; }
        public decimal IDis4 { get; set; }
        public decimal IDiscount4 { get; set; }
        public int IDI4CashierID { get; set; }
        public int IDI5 { get; set; }
        public decimal IDis5 { get; set; }
        public decimal IDiscount5 { get; set; }
        public int IDI5CashierID { get; set; }
        public decimal Rate { get; set; }
        public bool IsSDis { get; set; }
        public int SDNo { get; set; }
        public int SDID { get; set; }
        public decimal SDIs { get; set; }
        public decimal SDiscount { get; set; }
        public int DDisCashierID { get; set; }
        public decimal Nett { get; set; }
        public int LocationID { get; set; }
        public int DocumentID { get; set; }
        public int BillTypeID { get; set; }
        public int SaleTypeID { get; set; }
        public string Receipt { get; set; }
        public int SalesmanID { get; set; }
        public string Salesman { get; set; }
        public int CustomerID { get; set; }
        public string Customer { get; set; }
        public int CashierID { get; set; }
        public string Cashier { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public System.DateTime RecDate { get; set; }
        public int BaseUnitID { get; set; }
        public int UnitNo { get; set; }
        public int RowNo { get; set; }
        public bool IsRecall { get; set; }
        public string RecallNo { get; set; }
        public bool RecallAdv { get; set; }
        public decimal TaxAmount { get; set; }
        public bool IsTax { get; set; }
        public decimal TaxPercentage { get; set; }
        public bool IsStock { get; set; }
        public string SuspendNo { get; set; }
        public int SuspendBy { get; set; }
        public int CustomerType { get; set; }
        public int TransStatus { get; set; }
        public bool IsPromotionApplied { get; set; }
        public int PromotionID { get; set; }
        public bool IsPromotion { get; set; }
        public int InvPriceLevelID { get; set; }
        public string ItemSerial { get; set; }
        public string warranty { get; set; }
        public int TableNumber { get; set; }
        public int PrinterType { get; set; }
        public bool IsPritRpt { get; set; }
        public Nullable<int> ReferenceProductId { get; set; }
        public Nullable<int> ReferenceProductRow { get; set; }
        public bool IsAddonItem { get; set; }
        public bool IsTaxEnable { get; set; }
        public string TaxCode { get; set; }
        public string SplitItemReceiptNo { get; set; }
        public decimal Price { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string DeploCardNo { get; set; }
        public string KitchenCode { get; set; }
    }
}
