//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIT.HMS.HMSOrderTaker.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuspendHed
    {
        public int Idx { get; set; }
        public string SuspendNo { get; set; }
        public string Receipt { get; set; }
        public int LocationID { get; set; }
        public int UnitNo { get; set; }
        public System.DateTime STime { get; set; }
        public System.DateTime SDate { get; set; }
        public decimal Amount { get; set; }
        public int CashierID { get; set; }
        public bool IsRecall { get; set; }
        public string RecallReceipt { get; set; }
        public int RecallCashierID { get; set; }
        public string RecallCashier { get; set; }
        public int RecallUnitNo { get; set; }
        public System.DateTime RecallTime { get; set; }
        public int TransStatus { get; set; }
        public string TokenNumber { get; set; }
        public int NextBillDate { get; set; }
        public int CustomerId { get; set; }
        public int TableNumber { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string OrigSuspendNo { get; set; }
    }
}
