//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIT.HMS.HMSOrderTaker.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysCompany
    {
        public int SysCompanyID { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public int SysGroupOfCompanyId { get; set; }
        public string OtherBusinessName1 { get; set; }
        public string OtherBusinessName2 { get; set; }
        public string OtherBusinessName3 { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string ContactPerson { get; set; }
        public string Website { get; set; }
        public string TaxID1 { get; set; }
        public string TaxID2 { get; set; }
        public string TaxID3 { get; set; }
        public string TaxRegistrationNo1 { get; set; }
        public string TaxRegistrationNo2 { get; set; }
        public string TaxRegistrationNo3 { get; set; }
        public bool IsVat { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
    }
}
