//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIT.HMS.HMSOrderTaker.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysGroupOfCompany
    {
        public int SysGroupOfCompanyId { get; set; }
        public string GroupOfCompanyCode { get; set; }
        public string GroupOfCompanyName { get; set; }
        public string CompanyGmail { get; set; }
        public string CompanyVatNumber { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public byte[] CompanyLogo { get; set; }
        public string CompanyLogoType { get; set; }
        public string CompanyLogoName { get; set; }
    }
}
