//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIT.HMS.HMSOrderTaker.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDet
    {
        public int TransactionDetID { get; set; }
        public int ProductID { get; set; }
        public string ProductCode { get; set; }
        public string RefCode { get; set; }
        public int BarCodeFull { get; set; }
        public string Descrip { get; set; }
        public string BatchNo { get; set; }
        public string SerialNo { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public decimal Cost { get; set; }
        public decimal AvgCost { get; set; }
        public decimal Price { get; set; }
        public decimal Qty { get; set; }
        public decimal BalanceQty { get; set; }
        public decimal Amount { get; set; }
        public int UnitOfMeasureID { get; set; }
        public string UnitOfMeasureName { get; set; }
        public decimal ConvertFactor { get; set; }
        public int IDI1 { get; set; }
        public decimal IDis1 { get; set; }
        public decimal IDiscount1 { get; set; }
        public int IDI1CashierID { get; set; }
        public int IDI2 { get; set; }
        public decimal IDis2 { get; set; }
        public decimal IDiscount2 { get; set; }
        public int IDI2CashierID { get; set; }
        public int IDI3 { get; set; }
        public decimal IDis3 { get; set; }
        public decimal IDiscount3 { get; set; }
        public int IDI3CashierID { get; set; }
        public decimal IDI4 { get; set; }
        public decimal IDis4 { get; set; }
        public decimal IDiscount4 { get; set; }
        public int IDI4CashierID { get; set; }
        public int IDI5 { get; set; }
        public decimal IDis5 { get; set; }
        public decimal IDiscount5 { get; set; }
        public int IDI5CashierID { get; set; }
        public decimal Rate { get; set; }
        public bool IsSDis { get; set; }
        public int SDNo { get; set; }
        public int SDID { get; set; }
        public decimal SDIs { get; set; }
        public decimal SDiscount { get; set; }
        public int DDisCashierID { get; set; }
        public decimal Nett { get; set; }
        public int LocationID { get; set; }
        public int DocumentID { get; set; }
        public int BillTypeID { get; set; }
        public int SaleTypeID { get; set; }
        public string Receipt { get; set; }
        public int SalesmanID { get; set; }
        public string Salesman { get; set; }
        public int CustomerID { get; set; }
        public string Customer { get; set; }
        public int CashierID { get; set; }
        public string Cashier { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public System.DateTime RecDate { get; set; }
        public int BaseUnitID { get; set; }
        public int UnitNo { get; set; }
        public int RowNo { get; set; }
        public bool IsRecall { get; set; }
        public string RecallNO { get; set; }
        public bool RecallAdv { get; set; }
        public decimal TaxAmount { get; set; }
        public bool IsTax { get; set; }
        public decimal TaxPercentage { get; set; }
        public bool IsStock { get; set; }
        public int UpdateBy { get; set; }
        public int Status { get; set; }
        public int ZNo { get; set; }
        public int GroupOfCompanyID { get; set; }
        public int DataTransfer { get; set; }
        public int CustomerType { get; set; }
        public int TransStatus { get; set; }
        public System.DateTime ZDate { get; set; }
        public int IsPromotionApplied { get; set; }
        public int PromotionID { get; set; }
        public int IsPromotion { get; set; }
        public int LocationIDBilling { get; set; }
        public int TableID { get; set; }
        public int OrderTerminalID { get; set; }
        public int TicketID { get; set; }
        public int OrderNo { get; set; }
        public int IsPrinted { get; set; }
        public string ItemComment { get; set; }
        public int Packs { get; set; }
        public bool IsCancelKOT { get; set; }
        public int StewardID { get; set; }
        public string StewardName { get; set; }
        public decimal ServiceCharge { get; set; }
        public decimal ServiceChargeAmount { get; set; }
        public int ShiftNo { get; set; }
        public bool IsDayEnd { get; set; }
        public int UpdateUnitNo { get; set; }
        public int InvPriceLevelID { get; set; }
        public int Online { get; set; }
        public System.DateTime Deliverdate { get; set; }
        public decimal PackSize { get; set; }
        public string TourAgentCode { get; set; }
        public int TourAgentId { get; set; }
        public decimal TourAmount { get; set; }
        public decimal TourPrecent { get; set; }
        public decimal TourCommition { get; set; }
        public decimal TourCommitionPaidAmount { get; set; }
        public string TourAgentCompanyCode { get; set; }
        public int TourAgentCompanyId { get; set; }
        public decimal TourCompanyAmount { get; set; }
        public decimal TourCompanyPrecent { get; set; }
        public decimal TourCompanyCommition { get; set; }
        public decimal TourCompanyCommitionPaidAmount { get; set; }
        public decimal DelvryBalQty { get; set; }
        public decimal warranty { get; set; }
        public string ItemSerial { get; set; }
        public int CreditPeriod { get; set; }
        public decimal CopperratePrice { get; set; }
        public decimal SellingCopperratePrice { get; set; }
        public decimal AmountCopperratePrice { get; set; }
        public decimal NettCopperratePrice { get; set; }
        public bool IsCopperratePriceEnable { get; set; }
        public decimal RateCopperratePrice { get; set; }
        public bool IsBundleItem { get; set; }
        public int NextBillDate { get; set; }
        public decimal PackPrice { get; set; }
        public bool IsPackSale { get; set; }
        public decimal ExchageQty { get; set; }
        public string DeploCardNo { get; set; }
        public string ServingUnit { get; set; }
        public Nullable<int> TableNumber { get; set; }
        public Nullable<int> NoOfCustomers { get; set; }
        public Nullable<int> NoOfAdults { get; set; }
        public Nullable<int> NoOfChild { get; set; }
        public bool IsAddonItem { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public int StockLocationID { get; set; }
        public int ServingUnitId { get; set; }
        public string KitchenCode { get; set; }
    }
}
